# Depth pass data: summary sections 7-13
def C(q, o, a, e, l):
    return {"q": q, "options": o, "answer": a, "explanation": e, "level": l}

SEC = {}

SEC[7] = {
 "takeaway": "Universals exist in things concretely and in minds abstractly, but never abstractly and mind-independently at once — nothing abstract exists without abstraction.",
 "deepDive": "The single most important premise in the whole chapter lives here: there is **no third way** for a universal to exist — as both abstract and mind-independent. Everything later depends on it, so it is worth laying out as a grid.\n\nTake humanness. (1) *Concrete and mind-independent*: humanness as it exists in Socrates, bound up with his height, his snub nose, his being in Athens. (2) *Abstract and mind-dependent*: humanness as grasped by an intellect that has set Socrates’ individual features aside. (3) *Abstract and mind-independent*: humanness existing all by itself, in no individual and in no mind. The Aristotelian says box (3) is empty — that was Plato’s box, and the animality problem showed why nothing can occupy it.\n\nNow put that together with realism (step 5). If abstract objects are real, and if they can exist *as abstract* only in an intellect, then wherever there is a real abstract object there is an intellect grasping it. That is the hinge on which the chapter turns from “realism” to “minds.”\n\nOderberg’s squareness example helps with a natural protest: “But we never *meet* squareness!” Yes we do — in square things. What we never meet is squareness *in the abstract*, because that is not something out there to be met; it is something the intellect produces by abstracting from what it meets. A footnote adds the Scholastic picture of thinking behind this: to think of a thing is for the intellect to take on its form without its matter.\n\nNuances. Aristotelian realism does real work on **modality**: essences found in things fix what is possible, impossible, and necessary for them — an ordinary man can hold his breath for ten seconds but not ten hours; once dead, he cannot be revived by natural means. Mathematics too can be abstracted from the natures of things (two men plus two men make four). So Feser is not dismissing Aristotle; his objection (next section) is to an Aristotelianism that stops at *finite* minds.\n\nIn the formal argument, this section supplies the definition in step 8 and the key thesis that makes step 6’s options exhaustive. The usual confusion: because abstract universals exist only in minds, people conclude the Aristotelian view is “subjective.” But the *content* is drawn from things — the mind finds humanness in Socrates, it does not invent it.",
 "checks": [
  C("Which way of existing does Aristotelian realism say is impossible for a universal?", ["Concretely, in individual things", "Abstractly, in an intellect", "Abstractly and mind-independently at the same time", "Tied to individuating features"], 2, "There is no third way; being abstract is the result of an intellect’s abstraction.", "understand"),
  C("How can the Aristotelian ground the truth that an ordinary man cannot hold his breath for ten hours?", ["In human nature as it exists in individual men, grasped by the mind’s abstraction of humanness", "In a Platonic Form of Breath", "In linguistic convention", "In divine voluntarism"], 0, "Possibilities and necessities for a thing are grounded in its essence, which exists in the thing and is abstracted by the mind.", "apply"),
  C("Why is Aristotelian realism not conceptualism?", ["It denies universals are real", "It places universals in a third realm", "It holds universals exist only in God", "It holds universals really exist in extramental things, which the mind abstracts them from rather than inventing them"], 3, "The conceptualist says universals are wholly constructed by the mind; the Aristotelian says they exist in things.", "analyze")
 ],
 "terms": ["Aristotelian realism", "Abstraction", "Universal", "Essence (nature)", "Substance", "Modality (possibility and necessity)", "Intellect", "Concrete (vs. abstract)"]
}

SEC[8] = {
 "body": "But some abstract objects give the Aristotelian — at least one who stops at things and finite minds — serious trouble. Feser lists four kinds of case:\n\n- **Possibility with no world at all.** It is surely possible that no material world and no human minds had ever existed. Yet in that scenario it would *still* have been possible for a world and minds to come into being. What would ground that possibility? Not the essences of material things — there would be none — and not those essences as abstracted by human minds — there would be none of those either.\n- **Pure possibles.** Unicorns, centaurs, and mermaids never exist, yet they are possible, and unicornity and the like are (uninstantiated) universals. Their possibility cannot rest on the natures of actual unicorns (there have been none) or on human minds that imagine them (they were possible before anyone imagined them).\n- **Propositions true regardless of minds.** The proposition that there is no material world or human mind would be true if both vanished tomorrow, and would have been true had neither existed. Caesar’s assassination, and every historical truth, would stay true too.\n- **Necessary truths of mathematics and logic**, which would hold whether or not any world or human mind ever existed, and would survive their disappearance. What grounds *that* necessity?\n\nAll four share a structure. The Aristotelian has two grounding resources: natures existing in actual things, and those natures as abstracted by minds. Each case describes a truth or possibility that holds in a situation where neither resource is available, or that holds necessarily while the resources exist only contingently.",
 "takeaway": "Some possibilities and truths hold even in scenarios with no matter and no finite minds, so actual things and finite minds cannot be their ultimate ground.",
 "deepDive": "Why should a possibility need a *ground* at all? This is the hardest idea in the section, and it is worth being patient with.\n\nWhen we say “it is possible that a unicorn exists,” we are saying something true. True claims are true in virtue of something — something in reality answers to them. For actual kinds, the Aristotelian has a good answer: the possibilities for a man are fixed by human nature, which exists in actual men. But for the four cases, both of the Aristotelian’s resources fail.\n\nTry the **empty-stage test**. Imagine a scenario in which there has never been any matter and never any finite mind. Is it, in that scenario, possible for a world to come into being? Feser says surely yes. Now look for the Aristotelian ground: the essences of material things? None exist. Human minds abstracting those essences? None exist. The possibility is left with nothing to rest on — unless there is something beyond matter and finite minds.\n\nPure possibles make the same point in the actual world. Unicorns were possible before anyone ever imagined one. So imagination did not *make* them possible; it *discovered* that they are. (We cannot imagine a round square into possibility.) And there are no actual unicorns whose nature could ground it.\n\nNotice what Feser concedes: Aristotelian realism handles a great deal — the possibilities of actual kinds, and much of mathematics abstracted from things. His objection is targeted: these four cases need more. He is also careful that the necessary truths problem is about *necessity*: even if human minds happened always to exist, they *could* fail to, and a necessary truth cannot rest on something that might not be there.\n\nThis is the case for step 12, which secures step 13 (Aristotelian realism, so defined, is false). It also anticipates Welty’s necessity and plenitude conditions.\n\nThe usual confusion is to reply, “The possibility of unicorns is grounded in the atoms and genetics that could produce one.” But in the empty-stage scenario there are no atoms; possibilities with different physics are not grounded in actual physics; and no finite collection of things grounds a necessary truth. A second confusion is to think humanity as a whole, over all history, could serve — but it is just as contingent as any single human.",
 "checks": [
  C("Which case does Feser use to show that Aristotelian realism limited to finite minds is inadequate?", ["An ordinary man holding his breath for ten seconds", "Two men plus two men making four men", "Fido being an animal", "The possibility that a world could come into being even if no world or human minds had ever existed"], 3, "The other three are grounded in actual natures abstracted by human minds; the no-world possibility has neither ground available.", "apply"),
  C("Why can’t human imagination ground the possibility of unicorns?", ["Because unicorns were possible before anyone imagined them", "Because imagination is material", "Because unicorns are impossible", "Because only scientists can ground possibilities"], 0, "Imagining a unicorn discovers a possibility; it does not create it.", "understand")
 ],
 "terms": ["Pure possibles", "Uninstantiated universal", "Necessary truth", "Proposition", "Modality (possibility and necessity)", "Contingent", "Aristotelian realism", "Essence (nature)"]
}

SEC[9] = {
 "body": "This brings Feser to **Scholastic realism**, which he describes as essentially Aristotelian in spirit while giving at least a nod to Platonic realism. With Aristotle, it holds that universals exist only either in the things that instantiate them or in intellects that think them — there is no third realm independent of all intellects. With Plato, it agrees that there must be *some* realm distinct both from the material world and from human and other finite minds. Endorsing the thesis famously associated with Saint Augustine, it holds that universals, propositions, mathematical and logical truths, and necessities and possibilities exist in **an infinite, eternal, divine intellect**.\n\nSo on the Scholastic view abstract objects have three homes, but none is a mindless realm. Universals exist concretely in things (humanness in Socrates). They exist abstractly in finite intellects that abstract them (humanness in your mind as you read this). And the whole order of universals, propositions, and possibilities exists in the divine intellect — including those no finite mind ever entertains and those that would hold if no finite mind existed.\n\nThe Stage 1 argument is thus an argument by elimination: some realism must be true; Platonic and Aristotelian realism are in various ways inadequate; so Scholastic realism is correct — and since it entails an infinite divine intellect, there really is one. Feser notes that this is the basic thrust of what is sometimes called the **argument from eternal truths**, historically associated with Augustinian philosophy and defended also by thinkers like Leibniz. (His introduction adds that the idea has roots in Neo-Platonic thought.) Stage 2 then makes the reasoning more explicit.",
 "takeaway": "Scholastic realism keeps Aristotle’s rule that abstract objects exist only in things or in intellects, but adds Plato’s insight that some must exist beyond finite minds — in an infinite, eternal divine intellect.",
 "deepDive": "The hardest thing to see here is how Scholastic realism can agree with *both* Aristotle and Plato without contradiction. The key is to distinguish two different Platonic claims. Plato held (a) that there is a reality beyond matter and finite minds that grounds eternal truths, and (b) that this reality is a realm of mindless Forms. Aristotle rejected (b) — rightly, given the inertness and animality problems. The Scholastic accepts (a) and rejects (b). The eternal truths are real and beyond us, but they are *thoughts*, and the reality that holds them is an intellect.\n\nCompare three pictures of the number seven. **Plato:** seven exists as a Form in a realm by itself; groups of seven things imitate it. **Aristotle (finite minds only):** seven exists in groups of seven things, and as abstract only in minds that count and abstract. **Augustine and the Scholastics:** seven exists in groups of seven things, in finite minds that abstract it, *and* eternally as an idea in the divine intellect — which is why it would still be true that 3 + 4 = 7 if there were no groups and no finite minds.\n\nA common misreading is “Plato plus God”: God as a craftsman who looks up at independent Forms and copies them. That would leave a third realm standing, with God dependent on it. The Scholastic view is the reverse. The eternal truths are not outside God; they are God’s own understanding — which, given divine simplicity, is God himself.\n\nNuances. The Stage 1 conclusion rests on elimination, so its strength depends on three things: that the three versions are exhaustive (step 6), that Platonism fails (step 10), and that finite minds are inadequate (step 12). Also note Feser’s care in the introduction: this is an Augustinian proof, not an exegesis of Augustine’s texts.\n\nIn the formal argument this section corresponds to steps 9 and 14–15. Notice that God enters at step 15 only as “at least one necessarily existing intellect”; the full identification waits until step 27.\n\nThe usual confusion: people think the view makes the truths of math *created* by God, as if God could have made them otherwise. No — they are not creatures at all, and not products of an arbitrary choice; they are the eternal content of God’s intellect.",
 "checks": [
  C("What does Scholastic realism accept from Plato?", ["That universals exist in a mindless third realm", "That there must be a reality distinct from the material world and from finite minds", "That particular things are mere imitations of Forms", "That the Third Man argument is decisive"], 1, "It accepts that some reality beyond matter and finite minds is needed, but identifies it as a divine intellect, not a realm of Forms.", "understand"),
  C("On Scholastic realism, where does humanness exist?", ["Only in a Platonic Form", "Only in human minds", "Concretely in human beings, abstractly in finite intellects, and ultimately in the divine intellect", "Only in God, not in things"], 2, "Scholastic realism is Aristotelian in spirit: it keeps universals in things and finite minds and adds the divine intellect.", "recall"),
  C("Why is the Scholastic view not “Plato plus a God who copies the Forms”?", ["Because Scholastics deny that God exists", "Because the Forms would still be in a third realm", "Because Scholastics hold that God invented the Forms by arbitrary choice", "Because the eternal truths are God’s own understanding, not independent objects he consults"], 3, "No mindless realm remains; the truths are ideas in the divine intellect.", "analyze")
 ],
 "terms": ["Scholastic realism", "Argument from eternal truths", "Divine ideas", "Platonic realism", "Aristotelian realism", "Neo-Platonism", "Third realm", "Divine simplicity"]
}

SEC[10] = {
 "body": "Stage 2 makes the reasoning explicit. The arguments for realism showed that abstract objects (at least a great many of them) do not depend on the material world: material things are always particular, while triangularity and redness are universal; some propositions — especially logical and mathematical ones — hold whether or not the material world exists; the world is contingent while some truths are necessary; and some possibilities would remain possibilities whether or not the world existed. So they must exist in one of the two other ways: in an intellect (or intellects) or in a Platonic third realm. The third realm faces insuperable problems, so they exist in an intellect or intellects.\n\nBut not, ultimately, in **human** intellects, which are contingent: they come to be and pass away; once there were none, and someday there may be none again. Necessary truths, possibilities that would hold even if no human ever existed, universals that could be instantiated without humans, and propositions that would be true without humans cannot depend on us. Exactly the same goes for any **contingent creatures**. Suppose there are extraterrestrials with bodies radically unlike ours: because they too come into being, pass away, and could have failed to exist, the same reasoning applies to them. Suppose there are **angels**, pure intellects that never die: they are still contingent, since even an angel exists only if God creates it.\n\nThe underlying principle is simple: whatever depends for its existence on something that might not exist might itself fail to exist or hold. So the only kind of intellect on which abstract objects could ultimately depend is one that exists **with absolute necessity** — one that could not possibly have failed to exist.",
 "takeaway": "Because every created mind could fail to exist, only an intellect that exists with absolute necessity can be the ultimate ground of truths that hold necessarily.",
 "deepDive": "The engine of this section is a principle about dependence: **what depends on something contingent can be no more necessary than its ground.** Think of a shadow. A shadow depends on an object blocking light. If the object might not exist, the shadow might not exist either. If you found a shadow that *could not fail* to exist, you would know the thing casting it could not fail to exist.\n\nApply that to 2 + 2 = 4. Suppose its truth depended on human minds. Then in any situation without human minds, it would not be true. But it is true in every situation — that is what necessity means. So its truth cannot depend on human minds. Run the same test with any mind that could fail to exist, and you get the same result.\n\nNotice how thoroughly Feser closes the side doors. Aliens with radically different bodies: still contingent. Angels, who never pass away: still contingent. This last case teaches a distinction many people miss — between **everlasting** and **necessary**. Something could exist forever and still exist only because something else made it so. Necessity is about whether it *could* have failed to exist, not how long it lasts.\n\nTwo nuances. First, Feser’s word is “ultimately.” He is not denying that abstract objects exist in human minds — they do, whenever we think (step 9 says they exist in contingent intellects too). The claim is that finite minds cannot be their *ultimate* ground. Second, the argument’s first move repeats something easy to skip: abstract objects cannot simply be located in the material world, because material things are particular and the world is contingent. That is why the only candidates left are intellects and a third realm, and the third realm has already failed.\n\nIn the formal argument this reasoning backs step 12 and leads to step 15. It also sets up step 19, since “exists with absolute necessity” is exactly what will be shown to require pure actuality.\n\nThe usual confusion: “Why not the universe itself, or the laws of physics, as the necessary ground?” But the material world is contingent and particular, and its laws could have been otherwise — there are possible worlds with different physics. A second confusion is to hear “necessary intellect” and assume the argument has already reached God; it has not yet shown this intellect is one, omniscient, or omnipotent.",
 "checks": [
  C("Why can’t angels be the ultimate ground of necessary truths, even though they never die?", ["Because they are material", "Because they cannot think about mathematics", "Because everlasting is not the same as necessary: they exist only if created, so they are contingent", "Because they are Platonic Forms"], 2, "Necessity concerns whether a thing could have failed to exist, not how long it lasts.", "understand"),
  C("Feser says abstract objects cannot ultimately depend on human intellects. Does this mean they do not exist in human minds at all?", ["Yes — they exist only in God", "No — they exist in human minds when we think, but human minds are not their ultimate ground", "Yes — human minds only contain sentences", "No — they exist only in material things"], 1, "Step 9 says abstract objects exist in contingent intellects too; the claim is about ultimate dependence.", "analyze"),
  C("What principle drives the move from necessary truths to a necessarily existing intellect?", ["What depends on something that might not exist might itself fail to exist or hold", "Every effect resembles its cause", "Simpler explanations are always true", "Whatever is thought must be spoken"], 0, "A necessary truth cannot depend on a contingent ground, so its ultimate ground must be necessary.", "analyze")
 ],
 "terms": ["Necessary existence (absolute necessity)", "Contingent", "Angel (created pure intellect)", "Intellect", "Necessary truth", "Third realm", "Mind-independence", "Eternity (eternal)"]
}

SEC[11] = {
 "takeaway": "Because every universal and proposition is logically tied to every other, whatever grounds any of them must grasp all of them — an infinite system held by one conceptually omniscient mind.",
 "deepDive": "Why can’t the eternal truths be divided among several necessary minds? The answer turns on something subtle: **logical relations are themselves truths that need a home.**\n\nTry a concrete case. Suppose necessary mind A holds the proposition *all men are mortal*, and necessary mind B holds *Socrates is a man*. Now consider a third truth: *those two propositions together entail that Socrates is mortal.* Which mind holds that? It relates A’s proposition to B’s, so it can only be grasped by a mind that grasps both. Now generalize. However you try to divide the propositions among minds, there will be logical relations that cross the boundary — and there always are, because Feser points out that *every* proposition is either consistent or inconsistent with every other, and any two can be combined into compound propositions whose truth values follow the truth tables. So some mind must grasp relations that span the whole field — and a mind that grasps all the relations grasps all the propositions they relate. The committee collapses into one member who knows everything the committee was supposed to share.\n\nThe same holds for universals. Feser’s illustration — a human being as a rational animal — is explicitly just an example (“whether it is in fact correct is irrelevant”). The point is structural: grasping any universal adequately requires grasping the universals that define it, and those require others, so no universal can be held in isolation.\n\nThe system is also **infinite**. For every number there is a true proposition about whether it is odd or even, and a false one; and each of these is consistent or inconsistent with every other proposition. So the intellect that holds the system grasps infinitely many universals, propositions, and possible worlds.\n\nA key nuance: what is established here is **conceptual** omniscience — knowledge of all essences, possibilities, and necessary truths, in Robert Adams’s phrase. Whether this mind also knows contingent facts, like what happened yesterday, is a further question answered only in steps 24–25.\n\nIn the formal argument this section is steps 16–18 and 22–23. Note that uniqueness is secured *twice*: informally by the interlocking system, and formally by pure actuality (steps 19–21).\n\nThe usual confusion: people hear “omniscient” and assume the argument has already shown God knows everything about everyone. Not yet — Feser is careful to flag the qualification himself.",
 "checks": [
  C("Why do logical relations among propositions block dividing the eternal truths among several minds?", ["Because propositions are material", "Because logical relations are unimportant", "Because only humans grasp logic", "Because any division leaves relations crossing the boundary, which only a mind grasping both sides could hold"], 3, "Every proposition is consistent or inconsistent with every other, so some mind must grasp relations spanning the whole system.", "analyze"),
  C("How does Feser show the system of abstract objects is infinite?", ["For every number there is a true and a false proposition about whether it is odd or even", "Because the universe is infinite", "Because God is infinite by definition", "Because there are infinitely many languages"], 0, "The parity example guarantees infinitely many propositions, each logically related to all others.", "recall"),
  C("What kind of omniscience does the interlocking-system argument establish on its own?", ["Knowledge of every contingent fact", "Conceptual omniscience: knowledge of all essences, possibilities, and necessary truths", "Knowledge of the future only", "No kind of omniscience"], 1, "Adams’s “conceptual omniscience”; full omniscience needs steps 24–25.", "understand")
 ],
 "terms": ["Interlocking system", "Entailment", "Consistency (and inconsistency)", "Truth table (truth-functional compound)", "Conceptual omniscience", "Proposition", "Universal", "Possible world", "Truth value"]
}

SEC[12] = {
 "body": "A critic might still ask: could there be *more than one* conceptually omniscient intellect? Might such a mind know all necessary and possible truths but not contingent ones, making it omniscient only in a qualified sense? And why think it is omnipotent or perfectly good? Is this really God?\n\nFeser answers all three worries with a single move: **pure actuality**. An intellect that exists with absolute necessity must be purely actual. If its existence presupposed the actualization of some potential, it would be contingent on that actualization, and so would not exist of absolute necessity.\n\nChapter 1 showed what follows from pure actuality. What is purely actual is **unique**: two things of a kind must differ in something one has and the other lacks, and a purely actual being has no material or temporal features and no privations to differ by. It is **omnipotent**, since it is the source of all the actualizing power anything has. It is **perfectly good**, since badness is a privation — a failure to realize a potential — and it has none. It is **immutable**, since change is the actualization of potential; and therefore **immaterial**, **incorporeal**, and **eternal**.\n\nIt must also know **all** truths, contingent ones included — otherwise it would have an unactualized potential to know what it does not know, and would not be purely actual. (A footnote adds a second route: the actual is a subset of the possible, so a mind that knows all possible truths knows the actual ones too.)\n\nSo realism about abstract objects leads to one necessarily existing intellect that is omniscient, omnipotent, fully good, immutable, immaterial, incorporeal, and eternal: God. Chapter 6 later confirms that this intellect is one and the same as the Unmoved Mover of Chapter 1 and the necessary beings of the other proofs.",
 "takeaway": "A necessarily existing intellect must be purely actual, and pure actuality brings uniqueness, full omniscience, omnipotence, perfect goodness, immutability, immateriality, and eternity with it.",
 "deepDive": "The hardest step to see is the first: why does **necessary existence** require **pure actuality**? Unpack the phrase “its existence presupposes the actualization of some potential.” A human intellect is a good contrast. You exist only because countless potentials were actualized — your parents met, a cell divided, your body’s processes keep running right now. Your existence is *conditional*: it holds only if those actualizations occur. Anything whose existence is conditional in that way exists only contingently. So a being that exists with absolute necessity cannot have its existence hanging on any actualization at all. (Chapter 6 adds the same point from another angle: anything with parts of any kind — including a mixture of act and potency — depends on those parts being combined, and so is contingent.)\n\nNow the second hardest step: from pure actuality to **full omniscience**. Think of a student who has not learned calculus. She has a *potential* to know it — a capacity not yet realized. Ignorance, in general, is an unrealized potential to know. A purely actual being has no unrealized potentials. So there is nothing it does not know, including contingent facts. Feser’s footnote gives a second route: every actual truth is among the possible truths, so a mind that knows all possible truths already knows the actual ones.\n\nNotice the economy of this move. Three separate worries — maybe there are several such minds; maybe it knows only necessary truths; maybe it lacks power and goodness — are all answered by one idea borrowed from Chapter 1. That is why Feser can say the five proofs lead to one God rather than five deities: they converge on pure actuality.\n\nIn the formal argument this section covers steps 19–21 and 24–27, with steps 20 and 26 imported from Chapter 1.\n\nThe usual confusions. First, “pure actuality” does not mean frozen or static; it means lacking nothing that could be added — the opposite of inertness. Second, “necessary” here means absolutely necessary, not merely everlasting (recall the angels). Third, some worry that knowing contingent facts would make God depend on the world. Feser’s Chapter 6 explains that God knows the world as its cause — like an author who knows his story because he is writing it — not by observing it.",
 "checks": [
  C("Why must a necessarily existing intellect be purely actual?", ["Because it knows mathematics", "Because if its existence presupposed the actualization of some potential, it would be contingent on that actualization", "Because all intellects are purely actual", "Because Welty’s simplicity condition requires it"], 1, "Conditional existence is contingent existence; absolute necessity rules out any such condition.", "understand"),
  C("How does pure actuality yield knowledge of contingent truths?", ["God observes the world as it happens", "Contingent truths are really necessary", "Ignorance of any truth would be an unactualized potential to know it, which a purely actual being cannot have", "It does not; God knows only necessary truths"], 2, "Steps 24–25; the footnote adds that the actual is a subset of the possible.", "understand"),
  C("Which single idea answers the worries about multiple minds, limited knowledge, and lack of power or goodness?", ["The interlocking system", "Welty’s relevance condition", "The Third Man argument", "Pure actuality, imported from Chapter 1"], 3, "Uniqueness, full omniscience, omnipotence, and goodness all follow from pure actuality.", "analyze")
 ],
 "terms": ["Pure actuality", "Potentiality and actuality (potential, actual, actualize)", "Omniscience (unqualified)", "Omnipotence (omnipotent)", "Perfect goodness (fully good)", "Immutability (immutable)", "Immateriality and incorporeality (immaterial, incorporeal)", "Eternity (eternal)", "Unity (uniqueness)", "Privation", "Classical theism", "Conceptual omniscience"]
}

SEC[13] = {
 "body": "Feser notes that Greg Welty has defended a closely similar argument under the name **Theistic Conceptual Realism** (essentially Feser’s Scholastic realism; Welty uses “conceptualism” more broadly, to include Aristotelian realist views, and Feser judges their differences merely terminological). Welty lists six conditions an adequate theory must meet:\n\n1. **Objectivity** — abstract objects are real independently of human minds.\n2. **Necessity** — they exist necessarily, not contingently.\n3. **Intentionality** — they *represent*, as thoughts do: triangularity represents triangles, a proposition represents a state of affairs, a possible world represents a way things might have been.\n4. **Relevance** — the theory must help explain why there are the necessary and possible truths there are.\n5. **Plenitude** — it must posit enough abstract objects to do all the work they are supposed to do.\n6. **Simplicity** — it must not multiply kinds of entity beyond need.\n\nObjectivity requires realism rather than nominalism or conceptualism. Intentionality favors minds over a third realm, since it is easier to see how something could have representational content if it is in an intellect. Simplicity favors two realms (matter and intellects) over three. Necessity and plenitude favor Scholastic over merely Aristotelian realism, since finite minds are contingent and countless universals, propositions, and possibilities have never been entertained by any human. **Relevance** favors it too. Borrowing Welty’s example: a drawing of Socrates hammering nails may represent the possibility of Socrates being a carpenter, but it is silly to think Socrates could not have been a carpenter had the drawing never existed. Why would a third-realm “possible world” be any better as the thing that *makes* it possible? The Scholastic answer: a possible world is an idea in the intellect of an omniscient and omnipotent cause who *could have created* that world in accordance with the idea. God’s intellect, will, and power connect abstract objects to what can actually happen, as a third realm cannot.",
 "takeaway": "Judged by objectivity, necessity, intentionality, relevance, plenitude, and simplicity, only the view that abstract objects are ideas in God’s mind passes every test.",
 "deepDive": "Welty’s six conditions work best as a **scoreboard**, because each one separates a different pair of rivals.\n\n- *Objectivity* separates realism from nominalism and conceptualism.\n- *Intentionality* and *simplicity* separate mind-based views from Platonism.\n- *Necessity* and *plenitude* separate the divine intellect from finite minds.\n- *Relevance* separates the divine intellect from Platonism again, in a new way.\n\nOnly Scholastic realism (Welty’s Theistic Conceptual Realism) wins every row.\n\nThe hardest condition is **relevance**, which is really a question about **truthmakers**: what in reality makes a modal truth like “Socrates could have been a carpenter” true? Welty’s drawing shows that *representing* a possibility is not enough. The drawing depicts Socrates with a hammer, yet nobody thinks his possibly being a carpenter depends on that sketch. A Platonic possible world is in the same position: a representation in a realm that has no connection to Socrates or to anything that could act on him.\n\nNow compare an architect. A random sketch of a house on a napkin makes nothing buildable. But the same plan in the mind of a builder with materials and skill is connected to what can actually be built. The Scholastic says possible worlds are like the builder’s plans: ideas in the intellect of an omnipotent cause, who could make them real. That is why they genuinely ground what is possible. (This is also why the chapter’s final picture of God involves intellect, will, and power together, not intellect alone.)\n\nNuances. Welty himself focuses only on propositions and possible worlds (Feser’s footnote 14), and his use of “conceptualism” is broader than Feser’s — which is why Feser says their disagreement is merely terminological. Also notice that the intentionality point is independent of the earlier animality argument: even if a Platonist could answer the animality problem, he would still owe an account of how mindless objects are *about* anything.\n\nIn the formal argument, Welty’s conditions add support to steps 10 and 12. The usual confusions: mixing up the *simplicity condition* (don’t multiply kinds of entity) with *divine simplicity* (God has no parts), and hearing “intentionality” as “intention” (purpose). Here it means representation — aboutness.",
 "checks": [
  C("Which of Welty’s conditions most directly favors placing abstract objects in minds rather than a third realm because they represent things?", ["Plenitude", "Objectivity", "Necessity", "Intentionality"], 3, "Representation is intelligible in an intellect; mindless representation is mysterious.", "understand"),
  C("What is the point of the drawing of Socrates hammering nails?", ["A representation alone does not make something possible; an idea in the mind of an omnipotent cause can", "Socrates really was a carpenter", "Pictures are abstract objects", "The simplicity condition favors Platonism"], 0, "The relevance condition: third-realm worlds are no better truthmakers than drawings.", "analyze"),
  C("Which pair of conditions favors Scholastic over merely Aristotelian realism?", ["Intentionality and simplicity", "Necessity and plenitude", "Objectivity and intentionality", "Simplicity and objectivity"], 1, "Finite minds are contingent (necessity) and have never entertained most abstract objects (plenitude).", "recall")
 ],
 "terms": ["Welty’s six conditions", "Intentionality (Welty’s condition)", "Plenitude and relevance conditions", "Theistic Conceptual Realism", "Truthmaker", "Possible world", "Representation (aboutness)", "Omnipotence (omnipotent)"]
}
