# Depth pass data: summary sections 0-6
def C(q, o, a, e, l):
    return {"q": q, "options": o, "answer": a, "explanation": e, "level": l}

SEC = {}

SEC[0] = {
 "body_append": "\n\nNotice the three features Feser has quietly put on the table: universals are *shared by many* things at once, they are grasped by *setting individuality aside*, and they are *knowable without being perceivable*. Everything else in the chapter is an attempt to say what kind of reality could have all three features together.",
 "takeaway": "Everyday things are instances of general patterns — universals — which we can know truths about but cannot see or handle, and that makes them abstract objects.",
 "deepDive": "Feser’s opening claim is deliberately modest: universals exist *at least as objects of thought*. He is not assuming realism here. He starts from a datum that nominalists, conceptualists, Platonists, and Aristotelians all accept — we meaningfully talk about triangularity and know truths about it — and only later asks what kind of existence it has. Keep that sequence clear; skipping it makes the argument look as if it assumes its conclusion.\n\nTry a thought experiment. Picture five triangles: a wooden billiard rack, a stone pyramid face, a green paper cutout, an orange road sign, a triangle scratched in sand. Now state something you know: *anything triangular has three sides.* Which of the five is that knowledge about? None in particular — and all of them. It is also about every triangle that will ever be made, and every triangle that could be made but never will be. Your knowledge reaches beyond every particular you have met. That is the mark of a universal.\n\nNotice two nuances. First, Feser adds a qualifier to the angle-sum truth: *at least if it is Euclidean triangles we are talking about*. The truths about universals are precise and relative to exactly what is specified; they are not vague generalizations. Second, universals come in levels of generality. *Being a billiard ball* is shared only by billiard balls; *roundness* is shared by balls, globes, and the moon; *redness* crosses kinds entirely. This layering is an early glimpse of what Stage 2 calls the **interlocking system** (steps 16–17): universals are defined through, and connected to, other universals.\n\nHow does this feed the formal argument? It supplies the subject matter of step 1 — the abstract objects whose status is then disputed.\n\nThe usual confusion: people hear “abstract” and think *vague*, *unreal*, or *theoretical*. For Feser, “abstract” names the mental act of setting aside individual features. What is grasped that way is not fuzzy at all — triangularity has perfectly exact properties. A second confusion is to think the universal is just the *word* “triangle.” That is precisely the nominalist move Feser will dismantle (step 3).",
 "checks": [
  C("What makes universals “abstract,” in Feser’s explanation?", ["They are vague and imprecise", "We consider them by setting aside the individualizing features of particular things", "They exist only in the future", "They are made of a subtle kind of matter"], 1, "“Abstract” refers to abstracting from, or ignoring, what individualizes particular instances. Universals are precise, not vague.", "recall"),
  C("Feser’s claim that universals exist “at least as objects of thought” functions as:", ["The conclusion of the entire proof", "A proof of Platonic realism", "A modest starting point every party accepts, before the question of their mode of existence is raised", "A concession to nominalism that universals are unreal"], 2, "Everyone agrees we can think about and know truths about triangularity; the dispute is over what kind of existence it has.", "understand")
 ],
 "terms": ["Universal", "Particular (instance)", "Instantiation (exemplification)", "Abstraction", "Abstract object", "Problem of universals", "Euclidean geometry", "Interlocking system", "Individuating features (individuation)"]
}

SEC[1] = {
 "body": "**Propositions** are what sentences express: claims about the world that are true or false, distinct from the sentences used to state them. “John is a bachelor” and “John is an unmarried man” are two sentences with one proposition; so are the English “Snow is white” and the German “Schnee ist weiss.” What a mind entertains when it thinks is ultimately a proposition, not a string of words — which is why Socrates, speaking Greek in fifth-century B.C. Athens, and Barack Obama, speaking English in twenty-first-century Washington, can think exactly the same thing when each thinks that snow is white. A written sentence can be seen and erased; the proposition cannot. Wipe out every token of that sentence in every language and it would still be true that snow is white.\n\n**Numbers** likewise are not the marks we use for them. The numeral “2” is no more the number two than the Roman “II” is — any more than the name “Barack Obama” is the man. Numerals are labels. Erasing every numeral ever written would not make 2 + 2 = 4 false.\n\n**Possible worlds** are ways things could have been: Romney rather than Obama winning in 2012, Mars with three moons or one, a universe whose different physical laws produced no galaxies, unicorns existing alongside horses (or without them). What is possible in this sense is limited by logic, not by physics — physicists themselves consider alternative laws — so there is no possible world where 2 + 2 = 5 or where round squares exist. We can reason about possible worlds, but never visit or perceive them. So here too we have apparent abstract objects.",
 "takeaway": "Propositions, numbers, and possible worlds, like universals, are knowable but non-physical: none is identical to the sentence, numeral, or picture we use to represent it.",
 "deepDive": "The hardest idea here is the difference between a **representation** and **what is represented**. Feser runs the same test three times: find the physical thing (sentence, numeral, drawing), destroy it, and ask whether the abstract object is harmed. It never is.\n\nA worked example makes the sentence/proposition point vivid. Translate “Snow is white” into ten languages and write each on a card. How many sentences? Ten — different shapes, sounds, word orders. How many propositions? One. If you burn nine cards, you have lost nine sentences and no propositions. If you burn all ten, you still have not made snow stop being white.\n\nThere is a subtle nuance worth noticing. When Socrates and Obama each think that snow is white, there are *two acts of thinking*, occurring in two brains, in two eras. But there is *one content* being thought. Many people run these together and conclude that thoughts are private because thinkings are private. Feser’s point is about the content: it is shareable, and that shareability will later be the core of the case against conceptualism (step 4).\n\nNumbers follow the same pattern. A numeral is a *name*, like “Barack Obama.” Destroying every copy of a name does not destroy its bearer. Possible worlds add a twist: they are defined by logic, not physics. Feser stresses that physicists themselves entertain hypotheses about different physical laws, so “possible” here is broader than “physically possible.” Yet it is not unlimited — there is no possible world with round squares.\n\nWhere does this feed the argument? These are the abstract objects step 1 is about. Propositions and their logical relations are the backbone of steps 16–17; possible worlds and pure possibles drive step 12 and Welty’s relevance condition.\n\nCommon confusions: thinking a possible world is a real parallel universe (it is a way things could have been, not a place); thinking “possible” means “likely”; and thinking a proposition is a belief. A belief is a mental act that can be yours or mine; a proposition is what is believed, and it is the same for both of us.",
 "checks": [
  C("Which pair of sentences expresses a single proposition, according to Feser?", ["“Snow is white” and “Snow is cold”", "“Mars has two moons” and “Mars has three moons”", "“2 + 2 = 4” and “2 + 2 = 5”", "“John is a bachelor” and “John is an unmarried man”"], 3, "Different sentences can express one proposition; Feser’s examples include the bachelor pair and “Snow is white” / “Schnee ist weiss.”", "recall"),
  C("Which statement about possible worlds matches Feser’s account?", ["They are physically existing parallel universes", "They are limited by the actual laws of physics", "They are ways things could have been, limited by logic rather than physics", "They are simply sentences in books about alternate history"], 2, "Physicists consider different laws, so possibility here is not physical possibility; but logic rules out 2 + 2 = 5 and round squares.", "understand"),
  C("When Socrates and Obama both think that snow is white, what is shared?", ["One proposition, though the acts of thinking and the languages differ", "Only a sentence", "The same brain state", "Nothing — each has a private thought"], 0, "Two acts of thinking, one content. That shared content is the proposition, and its shareability later refutes conceptualism.", "understand")
 ],
 "terms": ["Proposition", "Numeral vs. number", "Possible world", "Abstract object", "Truth-bearer", "Modality (possibility and necessity)", "Mental state", "Scientific law (law of nature)"]
}

SEC[2] = {
 "body": "Granting that there are, in *some* sense, universals, propositions, numbers, and possible worlds, the real question is what kind of existence they have. Feser canvasses the tempting answers. Perhaps they are merely objects of human thought — conventional entities, constructs of our minds. Perhaps they are just useful fictions. Or perhaps they are material after all, only of an exotic sort — might a universal or a proposition simply be a brain process?\n\nFeser thinks there are compelling reasons to reject all of these and to embrace **realism**: abstract objects are real, cannot be reduced to anything material, and are not sheer constructs of the human mind. Notice that realism has one positive claim (they are real) and two negative ones (not material, not human-made). The two standard rivals each deny one piece. **Nominalism** denies that abstract objects are real at all — there are only particular things and the general words we use. **Conceptualism** grants that they are real but insists that they are wholly constructed by the human mind. A footnote adds that the positions can be mixed: someone might be a realist about numbers and a nominalist about possible worlds, so the arguments must address each kind of abstract object.\n\nIt is important what realism, at this stage, does *not* say. It does not yet say *where* or *how* abstract objects exist — in a Platonic realm, in things and minds, or in God. That is a separate question, taken up later.\n\nFeser’s case comes in two waves: six **direct** arguments showing that abstract objects have features (universality, necessity, infinity, independence from matter and from us) that the rivals cannot accommodate, and four **indirect** arguments showing that the rivals undermine themselves.",
 "takeaway": "The chapter’s first real question is not whether we can think about abstract objects but what kind of existence they have — and realism answers that they are real, non-material, and not human inventions.",
 "deepDive": "The hardest thing to hold in mind here is that **realism is deliberately noncommittal about location**. People hear “realism about abstract objects” and picture Plato’s heaven of Forms. But in Feser’s usage, Platonists, Aristotelians, and Scholastics are all realists. Step 5 (“some version of realism is true”) is compatible with every one of them; the fight over *where* abstract objects exist begins only at step 6.\n\nA decision tree helps. Question 1: are abstract objects real? If no, you are a **nominalist**. If yes, question 2: are they wholly products of human minds? If yes, you are a **conceptualist**. If no, you are a **realist**. Only then comes question 3: where do real, non-human-made abstract objects exist? That question splits realists into Platonic, Aristotelian, and Scholastic camps. The tree explains why step 1 claims to be exhaustive: every answer to questions 1 and 2 lands in one of three boxes.\n\nWhat about the option Feser mentions of identifying universals with brain processes? Run it through the tree. Brain processes are particular, located, contingent events in individual heads. If redness *is* such a process, then redness is not one thing shared by many and would not exist without brains — which makes it either not a genuine universal (nominalism) or a product of human minds (conceptualism). The one-over-many argument (step 2) then applies: redness is instantiated where no brain is aware of it.\n\nFeser’s footnote about mixed positions matters for strategy. Because someone might be a realist about mathematics but not about possible worlds, Feser offers arguments tailored to each kind of abstract object — geometry and arithmetic for numbers, a separate argument for propositions, another for possible worlds.\n\nThe usual confusion is about the word “conceptualism.” Everyone agrees we *have* concepts. Conceptualism is the stronger claim that universals are *nothing but* human concepts, with no foundation outside our minds. A second confusion is to think that denying abstract objects are human-made means denying they are *mental* in any sense. Keep that door open: the Scholastic will say they are mental — just not merely human.",
 "checks": [
  C("At step 5 (“some version of realism is true”), what has Feser NOT yet claimed?", ["That abstract objects are real", "That they are not sheer constructs of the human mind", "Where abstract objects exist — a third realm, finite minds, or a divine mind", "That nominalism fails"], 2, "Realism at step 5 is neutral among Platonic, Aristotelian, and Scholastic versions; step 6 raises the location question.", "analyze"),
  C("The suggestion that universals are simply brain processes is best classified as:", ["A version of Platonic realism", "One of the answers realism rejects, since it makes universals particular, material, and dependent on human minds", "Scholastic realism", "An instance of the Third Man argument"], 1, "Feser lists it among the answers “none of which can be correct.” Brain processes are particular and contingent; universals are shared and instantiated unobserved.", "apply")
 ],
 "terms": ["Realism (about abstract objects)", "Nominalism", "Conceptualism", "Fictionalism (useful fictions)", "Abstract object", "Problem of universals", "Mind-independence"]
}

SEC[3] = {
 "takeaway": "Abstract objects have features — universality, necessity, infinity, independence from matter and from us — that neither material things nor human minds can supply.",
 "deepDive": "The six arguments look like a list, but they share one logical form. Each identifies a **feature** of some abstract object and shows that neither the material world nor human minds could have that feature. One over many: a universal survives the destruction of every instance. Geometry: its objects are perfect, and its truths are necessary. Mathematics: its truths are necessary and its objects infinite. Propositions: some are true even in a scenario with no matter and no minds. Science: its laws are general and its facts objective. Possible worlds: many possibilities are prior to, or independent of, anything actual.\n\nHere is a thought experiment that runs several arguments at once — call it the **empty stage**. Imagine that tomorrow every material thing and every human mind ceases to exist. Now ask: is 2 + 2 = 4 still true? Is it still true that Caesar was assassinated on the Ides of March? Is it true that there is no material world and no human mind? Is it possible for a world to exist again? Almost everyone answers yes to all four. But then none of these truths depended on matter or on us.\n\nNotice Feser’s careful qualifications. He does not say *all* possibilities are independent of the actual world — only “much” of what is possible. He says that even many *contingent* propositions (like Caesar’s death) would survive, not just necessary ones. And the argument from mathematics adds something distinctive: the number series is **infinite**, whereas material things and human ideas are finite. That quantitative point will return in Stage 2, where the grounding intellect must grasp an infinite system (step 22).\n\nMost important of all — and the pivot of the whole proof — is what these arguments show independence *from*. They show that abstract objects do not depend on the material world or on *human* (finite) minds. They do **not** show independence from *every* mind. Many readers miss this and think the direct arguments already hand victory to Plato. They do not; they leave open whether some non-human mind is the ground.\n\nThese arguments are what step 2 summarizes, and they supply the materials for step 12 later. The usual confusion is to think they already prove God. They do not — a Platonist accepts every one of them. They establish realism; the rest of the chapter asks which realism.",
 "checks": [
  C("What do the six direct arguments show abstract objects to be independent of?", ["The material world and human (finite) minds", "Every possible mind, including God’s", "Logic", "Language only, but not minds"], 0, "This is the pivot of the proof: the arguments establish independence from matter and human minds, leaving open dependence on a non-human mind.", "analyze"),
  C("What distinctive point does the argument from mathematics add?", ["Numbers cause physical events", "Numbers are really numerals", "Mathematics is a convention", "The number series is infinite, while material things and human ideas are finite"], 3, "Besides necessity, Feser notes that an infinite series cannot depend on finitely many things or ideas.", "recall"),
  C("How would a Platonist respond to the six direct arguments?", ["Reject them all as question-begging", "Accept only the argument from science", "Take them to prove God’s existence", "Accept them, since they establish realism without settling where abstract objects exist"], 3, "The direct arguments establish realism. The Platonist agrees; the disagreement comes at steps 6–15.", "understand")
 ],
 "terms": ["One over many argument", "Necessary truth", "Contingent", "Proposition", "Possible world", "Universal", "Euclidean geometry", "Realism (about abstract objects)", "Scientific law (law of nature)", "Mind-independence"]
}

SEC[4] = {
 "body": "Nominalism says that where we think there are universals, there are really just general *names*: the word “red,” but no such thing as redness. The obvious question is why we apply “red” to exactly these things. The natural answer — because they all have redness — brings universals right back. The nominalist may instead say the things simply *resemble* one another, without saying in what respect. That is implausible on its face (surely they resemble each other *in their redness*), and it runs into two deeper problems.\n\n7. **The vicious regress problem.** As Bertrand Russell pointed out, resemblance is itself a universal. A stop sign resembles a fire truck; grass resembles the Incredible Hulk’s skin; each is a case of one and the same thing, resemblance. If the nominalist says these cases of resemblance are merely called “resemblance” because they resemble one another, we now have a higher-order resemblance — another universal — and the same move just regenerates the problem at each level, forever.\n8. **The “words are universals too” problem.** The nominalist says there are no universals, only general words like “red.” But the *word* “red” is a universal: when you, I, and Socrates each say “red,” those are three tokens of one word type. That is the only reason the view ever seemed plausible — one word applying to many things mimics the sense that they have something in common. Deny it, and say our utterances are merely resembling words, and you get absurdity: nobody ever uses the same word twice, even talking to themselves, so communication is impossible — in which case what is the nominalist doing trying to convince us? And the appeal to resemblance reopens the regress.\n\nThe general lesson: nominalism is notoriously hard to state without sneaking universals or other abstract objects in through the back door, which makes it self-undermining.",
 "takeaway": "Nominalism cannot explain why one word applies to many things without appealing to something shared — resemblance, or the word itself — so it smuggles back the universals it denies.",
 "deepDive": "Russell’s regress is easy to state and easy to misunderstand, so walk it slowly.\n\n*Level 0.* We have red things: a stop sign, a fire truck, a cherry. The nominalist says we call them all “red” because they resemble one another.\n\n*Level 1.* Look at the resemblances themselves: stop sign–fire truck, cherry–ruby, and (for green) grass–Hulk. Each is a case of *resemblance*. Is resemblance a universal — one thing present in many cases? If the nominalist says yes, he has admitted a universal and nominalism is over.\n\n*Level 2.* So he says no: these resemblances are merely called “resemblance” because *they resemble each other*. But now we have a second-order resemblance among resemblances, and the same question arises about it. He faces exactly the same choice again.\n\nThe regress is **vicious**, not harmless, because at no level does the nominalist actually explain what he promised to explain. Each level’s account is borrowed from the next, and the debt is never repaid. (Contrast a harmless regress, like the endless series of truths “p is true,” “it is true that p is true,” and so on, where nothing at any level depends on the next for its explanation.)\n\nThe “words are universals too” problem is even more direct. The nominalist replaces redness with the *word* “red.” But the word is itself one type with many tokens. Feser’s point is that this is not a minor slip; it is *the* reason nominalism ever sounded plausible. If the nominalist bites the bullet — each utterance is a different word that merely resembles the others — he loses the ability to say anything. Notice a further consequence (a point in the spirit of Feser’s): even logic would collapse, because an argument’s validity depends on the *same* term recurring in premises and conclusion.\n\nHow this feeds the argument: this section defends step 3. The usual confusion is to treat nominalism as mere hard-headed common sense (“there are just things and words”). Russell’s point shows the common-sense appeal to resemblance is already a commitment to a universal. A second confusion is to think the debate is “just semantics” — but it is precisely the status of semantics, of shared words and meanings, that is at issue.",
 "checks": [
  C("Why does appealing to resemblance fail to save nominalism?", ["Resemblance is itself a universal, and treating resemblances as merely resembling each other regenerates the problem at every level", "Resemblance cannot be observed", "Only red things resemble each other", "Resemblance is a Platonic Form in a third realm"], 0, "This is Russell’s vicious regress: each attempt to avoid the universal resemblance posits a higher-order resemblance.", "understand"),
  C("Why is the nominalist’s own word “red” a problem for him?", ["Words are material, so they cannot refer", "The word is one type with many tokens — a one-over-many situation — and denying this makes communication impossible", "The word “red” is ambiguous", "Words exist only in the future"], 1, "Your, my, and Socrates’ utterances are tokens of one word; if they are merely resembling words, no one ever uses the same word twice.", "understand"),
  C("What makes Russell’s regress vicious rather than harmless?", ["It involves infinitely many objects", "It was discovered by Russell", "At no level is the promised explanation actually delivered; each level borrows it from the next", "It concerns colors"], 2, "An infinite series is not bad in itself; it is vicious when each step’s explanation depends on a further step that never completes it.", "analyze")
 ],
 "terms": ["Nominalism", "Resemblance nominalism", "Type vs. token", "Universal", "Particular (instance)", "One over many argument", "Vicious regress"]
}

SEC[5] = {
 "body": "Conceptualism tries to split the difference: universals exist, but only in human minds. Feser thinks it faces what are widely regarded as insuperable difficulties.\n\n9. **The objectivity of concepts and knowledge.** When you and I think of redness or triangularity, we entertain *one and the same* concept, referring to one and the same universal — not two private concepts with nothing in common. When we both think of the Pythagorean theorem, we think of one truth, not “your” theorem and “mine.” We share concepts and truths with the long dead and with people not yet born; if humanity died out and new intelligent beings arose, they could grasp the very same ones. So these have a foundation outside the human mind. The same point shows up in **communication**: if the concepts and propositions you express were private constructs, your idea of snow and mine would never be the same, and we could never mean the same thing by anything we said. But we plainly can — indeed we must, even to agree or disagree about conceptualism.\n10. **The incoherence of psychologism.** Gottlob Frege fought **psychologism**, the view that the laws of logic and mathematics are just psychological laws describing how human minds happen to work, rather than truths about reality. Add the relativist twist that our minds are shaped by contingent, changing biological, social, historical, and cultural forces, and you get a radical relativism in which logic, math, and science are all culturally conditioned and revisable. That view refutes itself: to explain *how* evolution or culture shaped our minds, you must invoke universals (selection pressures, class interests, genetic mutations, social trends), scientific and mathematical principles, and standards of logic — the very things the view says lack objective validity and did not exist before our minds did.\n\nThe less radical, **Kantian** version says our concepts and logic reflect only our own minds’ structure, but *necessarily* so, unchangeable by evolution or culture. This still fails. Its defender must explain how he knows this and how our minds came to be so. If he uses concepts and logic he has just declared cut off from reality, he undermines his case. If he claims to know the necessary, objective structure of our minds, he claims exactly the kind of objective knowledge his theory rules out. Either way he is caught: deny objective validity and he cannot defend his view; affirm it and he contradicts his view in the act of defending it.",
 "takeaway": "If concepts were private human constructions, no two people could share a thought or communicate, and every argument for the view would rely on the objective concepts and logic it denies.",
 "deepDive": "The hardest idea here is the **self-refutation** at the heart of psychologism, and it becomes clear once you separate two questions: *how did we come to think this way?* (a causal history) and *is what we think valid?* (a question of truth).\n\nConsider a calculator. You can tell a long story about how it was designed, manufactured, and shipped. None of that story settles whether 7 × 8 = 56. The correctness of the output is judged by arithmetic, not by the calculator’s history. Now the relativist offers a history of human minds: evolution and culture shaped us to reason as we do. Suppose that story is true. It still cannot show that our logic lacks validity — and worse, *telling* the story requires the validity it denies. To say “selection pressures produced our logical habits,” you must use universals (selection pressure, mutation, trend), rely on biological and mathematical laws, and draw inferences you expect your listener to accept as valid. If those are merely local habits, so is the argument.\n\nThe **Kantian** version is subtler. It concedes that our mental structure is fixed and universal, not culturally variable. Feser’s dilemma: the Kantian claims to *know* something objective — the necessary structure of our minds. Either our concepts and logic give objective knowledge (then his general thesis that they do not reach objective reality is false), or they do not (then he cannot know his thesis). He cannot have it both ways.\n\nNuances. Feser is not denying that biology or culture influence *how we express* or *come to grasp* truths. His target is the claim that validity *reduces to* those influences. And note what the objectivity argument concludes: concepts and propositions have a foundation *outside the human mind*. It does not say outside *every* mind — which is exactly the opening the Scholastic will use.\n\nThis section defends step 4. The usual confusion is to lump conceptualism together with Aristotelian realism, since both put abstract universals in minds. The difference is decisive: the conceptualist says nothing in things answers to our concepts; the Aristotelian says universals exist in things and the mind abstracts them. Another confusion: thinking “we communicate well enough with similar concepts.” But “similar in which respect?” reintroduces a shared concept.",
 "checks": [
  C("Feser’s objection to evolutionary or cultural psychologism is best stated as:", ["Evolution never happened", "Culture has no influence on thought", "Explaining our logic this way requires appeal to universals, scientific principles, and logical standards that the view says lack objective validity", "Kant already disproved it"], 2, "The view undermines itself: its own explanation presupposes what it denies.", "understand"),
  C("What is the dilemma facing the Kantian conceptualist?", ["If our concepts lack objective validity, he cannot defend his view; if they have it, he has claimed objective knowledge his view rules out", "Either God exists or minds evolved", "Either universals are in things or in Forms", "Either logic is innate or learned"], 0, "He must either give up the means of defending his view or contradict it in defending it.", "analyze"),
  C("What exactly does the argument from the objectivity of concepts conclude?", ["That universals exist in a Platonic third realm", "That concepts and propositions have a foundation outside the human mind", "That God exists", "That concepts are brain states"], 1, "It concludes independence from human minds, leaving open whether some non-human mind grounds them.", "analyze")
 ],
 "terms": ["Conceptualism", "Psychologism", "Radical relativism", "Kantian conceptualism", "Proposition", "Universal", "Aristotelian realism", "Modus ponens"]
}

SEC[6] = {
 "takeaway": "Platonic Forms, existing apart from all minds, could not act, could not be known, could not be both universal and individual, and would drain real things of their natures — so abstract objects cannot exist independently of every mind.",
 "deepDive": "The objection Feser calls “more telling” — the **animality problem** — is the one to master, because it shows not just that Platonism is awkward but that a universal *cannot* exist as a self-standing thing.\n\nA universal is general because it leaves certain things open. *Animality* leaves open whether the animal is rational or not; that is exactly why it can be shared by Socrates and Fido. An individual thing, by contrast, is fully determinate: whatever actually exists as a thing is determinately rational or determinately not. There is no existing animal that is neither. So if animality existed as an individual object in its own right — which is what a Platonic Form would be — it would have to be an existing thing that is neither rational nor nonrational. That is impossible. The generality that makes animality a universal is exactly what prevents it from existing on its own.\n\nA quick exercise helps. Try to imagine “an animal in general” — not a dog, not a human, not a bird. Whatever you picture has some number of legs and some color, and so turns into a particular animal. (Universals can be *conceived* by the intellect, but not *pictured*; and they certainly cannot *exist* as undetermined individuals.)\n\nThe **causal inertness** objection has two prongs worth separating. The *epistemic* prong: if a Form affects nothing, how could we know about it? The *explanatory* prong: if a Form affects nothing, how could it explain why a billiard rack is triangular? Even Platonists who deny that knowledge requires causal contact still owe an answer to the second.\n\nFeser’s treatment of the **Third Man** is deliberately modest: Plato raised it himself, and its force has been disputed for millennia. The **mirror-image** objection draws on the Aristotelian notion of **substance**: trees and humans exist in their own right with intrinsic natures, and are not images of something located elsewhere.\n\nThis section defends step 10 and so secures step 11. Welty’s intentionality, simplicity, and relevance conditions later add further support.\n\nThe usual confusion: when mathematicians call themselves “Platonists,” they usually mean only that numbers are real and discovered. Feser agrees with *that*; it is realism. What he rejects is the claim that abstract objects exist *independently of every mind*. Scholastic realism even keeps one Platonic insight — that there is a reality beyond matter and finite minds.",
 "checks": [
  C("Why does the animality problem show that animality cannot be a Platonic Form?", ["Because animals are material", "Because Plato never discussed animals", "Because animality must in itself be neither rational nor nonrational, but no existing individual can be neither", "Because animality is causally inert"], 2, "A universal leaves differences open; an individual is determinate. A Form would be an individual that is somehow undetermined — impossible.", "understand"),
  C("What are the two prongs of the causal inertness objection?", ["Forms are too many and too few", "Forms cause too much and too little", "Forms are material and mental", "If Forms affect nothing, we could not know them, and they could not explain why particulars conform to them"], 3, "Feser raises both the knowledge problem and the explanation problem.", "analyze"),
  C("A mathematician says, “I’m a Platonist: numbers are real and we discover truths about them.” How much of this does Feser reject?", ["None of it as stated — that is just realism; he rejects only the claim that abstract objects exist independently of every mind", "All of it", "Only the claim that we discover mathematical truths", "Only the claim that numbers are real"], 0, "Feser accepts realism and discovery; his target is the mind-independent third realm.", "apply")
 ],
 "terms": ["Platonic realism", "Form (Platonic) and participation", "Third realm", "Causal inertness", "Third Man argument", "Substance", "Essence (nature)", "Benacerraf’s problem", "Determinate vs. determinable (general)"]
}
