# Depth pass data: summary sections 14-18
def C(q, o, a, e, l):
    return {"q": q, "options": o, "answer": a, "explanation": e, "level": l}

SEC = {}

SEC[14] = {
 "body": "Feser then condenses the reasoning into twenty-nine steps (restated in full in the Argument section of this module). Because the argument grew out of the long debate over universals, it has taken several twists and turns, but its skeleton is simple: two eliminations followed by a deduction.\n\n**First elimination (steps 1–5).** There are only three accounts of abstract objects — realism, nominalism, conceptualism. Realism has decisive arguments in its favor; nominalism and conceptualism face insuperable objections. So some version of realism is true.\n\n**Second elimination (steps 6–15).** Realism comes in three versions — Platonic, Aristotelian, Scholastic — defined by where abstract objects exist: in a third realm, only in contingent intellects, or also in a necessary intellect (steps 7–9 are definitions). The third-realm claim and the contingent-minds-only claim both face insuperable objections (steps 10 and 12), so Platonic and Aristotelian realism are false (11, 13) and Scholastic realism is true (14): abstract objects exist in at least one necessarily existing intellect (15).\n\n**Deduction (steps 16–29).** Abstract objects form an interlocking system, which must exist as a whole in a necessary intellect (16–18). A necessary intellect is purely actual, and only one thing can be purely actual, so there is exactly one (19–21). It is conceptually omniscient (22–23) and, since ignorance would be unrealized potential, omniscient without qualification (24–25). Pure actuality also brings omnipotence, goodness, immutability, immateriality, incorporeality, and eternity (26), so there is exactly one such intellect with all these attributes (27) — which is what it is for God to exist (28–29).\n\nThe premises that carry the weight are 2–4, 10, 12, 16–17, 19–20, 24, and 26; the rest are definitions or inferences.",
 "takeaway": "The 29 steps are two eliminations — first of realism’s rivals, then of realism’s non-theistic versions — followed by a deduction of God’s attributes from pure actuality.",
 "deepDive": "A long formal argument can feel like a wall of numbered sentences. The way to master it is to ask: **where would a critic have to push to escape the conclusion?** Think of the argument as a building with six exit doors, each deliberately locked.\n\n- **Door 1: nominalism** — “abstract objects aren’t real.” Locked by step 3 (Russell’s regress; words are universals too).\n- **Door 2: conceptualism** — “they’re real but human-made.” Locked by step 4 (shared concepts, communication, the self-refutation of psychologism).\n- **Door 3: Platonism** — “they’re real and exist in no mind.” Locked by step 10 (inertness, the Third Man, animality, natures exiled from things).\n- **Door 4: finite minds** — “they’re in human or other created minds.” Locked by step 12 (pure possibles, possibility without a world, truths without minds, necessary truths).\n- **Door 5: a committee** — “several necessary minds share them.” Locked by steps 16–17 and 19–21 (the interlocking system; the uniqueness of pure actuality).\n- **Door 6: “that’s not God”** — “a cosmic mathematician, not the God of theism.” Locked by steps 19, 24, and 26 (pure actuality brings full omniscience and every divine attribute).\n\nA critic who wants to reject the conclusion must pick a door and show the lock fails. That is a far more productive conversation than a vague “I’m not convinced.”\n\nTwo nuances. First, steps 1 and 6 claim **exhaustiveness** — only three accounts, only three versions of realism. A critic may propose something new (fictionalism, brute modal facts). The Feserian reply is that each new proposal turns out to be a variant of an existing option: fictionalism denies reality (nominalism), brute mind-independent modal facts are Platonism under another name. Second, steps 7–9 are **definitions**, so the substantive work is done by 10 and 12. People sometimes attack step 8 (“Aristotle believed in a divine mind!”), but in the argument “Aristotelian realism” just names the view that stops at contingent minds.\n\nThe usual confusion is to think the proof is a single leap from “2 + 2 = 4” to God. It is a chain of eliminations, each backed by pages of argument. Its strength lies in how many independent considerations close each door.",
 "checks": [
  C("Which steps in the formal argument are essentially definitions rather than substantive premises?", ["Steps 7–9", "Steps 2–4", "Steps 10 and 12", "Steps 19–20"], 0, "Steps 7–9 say what each version of realism holds; the substantive objections are in 10 and 12.", "recall"),
  C("A critic says, “Abstract objects are just brute necessary facts that exist in no mind.” Which step must he attack?", ["Step 3", "Step 10, the objections to a mind-independent third realm", "Step 26", "Step 28"], 1, "Real, necessary, mind-independent abstract objects are Platonism in substance, so the critic must defeat step 10.", "apply"),
  C("Where in the formal argument do Chapter 1’s results enter?", ["Steps 1 and 6", "Steps 7–9", "Steps 16–17", "Steps 20 and 26"], 3, "Step 20 (uniqueness of pure actuality) and step 26 (the other attributes) are imported from Chapter 1.", "recall")
 ],
 "terms": ["Argument by elimination (disjunctive syllogism, modus tollens)", "Scholastic realism", "Pure actuality", "Conceptual omniscience", "Interlocking system", "Classical theism", "Unity (uniqueness)"]
}

SEC[15] = {
 "body": "Feser notes that the debate over abstract objects is over 2,300 years old and entangled with the metaphysics of modality, philosophy of mathematics, and philosophy of language, so he cannot address everything nominalists, conceptualists, or Platonists might say. He takes up several objections aimed specifically at Scholastic realism.\n\nSome critics (Keith Yandell and William Lane Craig, responding to Welty) say that if universals, propositions, and possible worlds are ideas in God’s mind, they are not really *abstract* objects at all but concrete ones. Following Welty, Feser replies first that there is simply no consensus among contemporary metaphysicians about what abstract objects are, so the objection has no settled, neutral definition to lean on. Second, even if there were such a consensus, the objection would beg the question: for Aristotelian and Scholastic realists, an abstract object just *is* what an intellect produces when it abstracts from particulars. The critic says an abstract object cannot exist in an intellect; the Scholastic says it can exist *only* in an intellect. Merely asserting the first does not refute the second; it assumes it false.\n\nIn a footnote Feser diagnoses the clash: contemporary philosophers tend to treat thinking as having a “mental state,” a concrete particular in the brain or in a Cartesian soul, whereas for Aristotelians and Scholastics to think is to take on the form of a thing without its matter. They also draw the abstract/concrete line differently — moderns often as outside versus inside space and time, with each thing simply one or the other; Aristotelians in terms of the intellect’s act of abstraction, so the same humanness or redness can exist concretely in things and abstractly in an intellect.",
 "takeaway": "Calling divine ideas “concrete” works only on a contemporary definition of “abstract” that the Scholastic rejects; simply asserting that definition begs the question.",
 "deepDive": "This objection is really a clash between two **definitions of “abstract,”** and it dissolves once you see both side by side.\n\n**Contemporary definition.** An abstract object is non-spatiotemporal and causally inert, and in particular is *not* a mental item. Everything is either abstract or concrete, full stop. Thoughts are concrete: they are mental states, particular events in brains or souls.\n\n**Aristotelian-Scholastic definition.** “Abstract” describes the way a nature exists when an intellect has *abstracted* it — considered it apart from the individual features it has in things. The very same nature can exist in two modes: concretely (humanness in Socrates) and abstractly (humanness in your understanding). On this view, abstract objects are *essentially* tied to intellects.\n\nWork through an example. You think about humanness. The contemporary philosopher sees two things: a concrete mental state in your head, and (maybe) an abstract object out in a Platonic realm that the state is about. The Scholastic sees one nature, humanness, existing in you in the abstract mode — the form received without the matter. On the first picture, locating humanness in a mind turns it into a concrete mental state. On the second, locating it in a mind is precisely what makes it abstract.\n\nFeser’s reply therefore has two prongs. First, the contemporary definition is not a neutral consensus — metaphysicians disagree about what abstract objects are (Welty’s point). Second, using that definition against the Scholastic assumes the very thing in dispute. It is like arguing “your view is false because my view is true.”\n\nA nuance worth adding: even if someone insists on calling divine ideas “concrete,” what has been lost? The divine ideas are universal in content, necessary, eternal, and non-physical — everything the Platonist wanted abstract objects to be, minus the mindless realm. The dispute then looks largely verbal.\n\nThis defends the Scholastic reading of steps 9 and 15. The usual confusion: imagining God’s thoughts as a stream of separate mental events like ours. Given divine simplicity, God’s understanding is not a series of particular states at all.",
 "checks": [
  C("What does the objection that divine ideas are “concrete” assume?", ["That God does not exist", "That Platonic realism is false", "The contemporary definition on which abstract objects are non-mental and everything is either abstract or concrete", "That nominalism is true"], 2, "The Scholastic defines “abstract” by the intellect’s act of abstraction, so the objection begs the question.", "analyze"),
  C("On the Aristotelian-Scholastic view, how can humanness be both concrete and abstract?", ["It exists concretely in individual humans and abstractly in an intellect that abstracts it", "It cannot; that would be a contradiction", "It is concrete in God and abstract in humans", "It is abstract in a third realm and concrete in the brain"], 0, "The same nature exists in two modes, depending on whether the intellect has abstracted it.", "understand")
 ],
 "terms": ["Abstract object", "Concrete (vs. abstract)", "Mental state", "Cartesian substance (Cartesian dualism)", "Divine ideas", "Abstraction", "Divine simplicity", "Intellect"]
}

SEC[16] = {
 "body": "Brian Leftow criticizes “deity theories,” which ground possibility and necessity in God’s nature. Scholastic realism is one: since God is simple (noncomposite), his intellect, power, goodness, and nature are really one and the same, so grounding necessities in divine ideas is grounding them in the divine nature. Leftow accepts this for pure logic and mathematics but balks at other necessary truths. Suppose it is necessary that water = H₂O. On a deity theory, that necessity follows from God’s nature, so if God exists, water is necessarily H₂O. But then, Leftow says, if it were *not* necessary that water = H₂O, God would not exist — making God’s existence depend on facts about water, which is counterintuitive.\n\nFeser replies with a parallel. It is necessary that 2 + 2 = 4, so it is necessary that two rocks added to two rocks make four rocks. By Leftow’s pattern, if that rock truth were not necessary, 2 + 2 = 4 would not be necessary — so arithmetic “depends” on rocks. Obviously it does not in any interesting sense: mathematics entails necessary truths about rocks as about everything else, and because they are necessary, mineralogy will never overturn them. Likewise the divine nature entails necessary truths about water, and hydrology will never overturn them. Leftow does not claim that hydrology could falsify God’s existence — but then it is very unclear what the supposedly counterintuitive “dependence” amounts to.\n\nFurther, why take seriously the antecedent “if it were not necessary that water = H₂O”? If someone proposed to consider a scenario in which 2 + 2 does not necessarily equal 4, we should object that there is no such scenario to consider. The deity theorist can say the same about water (a point Feser credits to Welty). Leftow, a **voluntarist** who thinks such necessities come from God’s will, might say it would not have been necessary had God willed otherwise — but that simply begs the question against deity theorists, who reject voluntarism.",
 "takeaway": "That God’s nature entails necessary truths about water no more makes God depend on water than arithmetic depends on rocks — entailment is not dependence.",
 "deepDive": "The hardest idea here is why **contraposition does not reveal dependence**. Contraposition is a logical rule: “if P then Q” is equivalent to “if not-Q then not-P.” Leftow starts from “if God exists, water is necessarily H₂O” and contraposes to “if water is not necessarily H₂O, God does not exist.” Logically impeccable. The mistake is to read the second sentence as saying God’s existence *rests on* water.\n\nA famous illustration from the philosophy of science (not from Feser, but it makes his point vivid) is the flagpole and its shadow. Given the sun’s angle, the height of the pole fixes the length of the shadow — and, by the same geometry, the length of the shadow “fixes” the height of the pole. But the shadow does not *explain* or *ground* the pole; the pole explains the shadow. Logical connections run both ways; explanation and dependence run one way. Feser’s rocks example makes the same point with necessary truths: arithmetic entails truths about rocks, but nobody thinks arithmetic is held up by mineralogy.\n\nThe second prong targets Leftow’s “if” clause. Conditionals with **impossible** antecedents are strange: if 2 + 2 did not necessarily equal 4, anything at all might “follow.” Feser (following Welty) says the right response is not to entertain the scenario but to deny there is one. If water’s being H₂O is necessary, “suppose it weren’t” describes nothing.\n\nThe third prong is the most revealing. Leftow can make the antecedent seem entertainable only by assuming **voluntarism**: necessities about water come from God’s *will*, so God could have willed otherwise. But the deity theorist grounds them in God’s *nature* and intellect, not in arbitrary choice. Assuming voluntarism to refute a deity theory begs the question.\n\nNuances: Leftow grants deity theories for logic and mathematics; his worry is about other necessities. And the whole deity theory depends on divine simplicity — without it, “grounded in God’s ideas” and “grounded in God’s nature” would come apart.\n\nThis defends the coherence of steps 9 and 15. The usual confusion: thinking “grounded in God’s nature” means God could change the truths. It means the opposite — they are as unchangeable as God is. People also sometimes think a truth learned by experience (water = H₂O) must be contingent; how we learn a truth does not settle whether it is necessary.",
 "checks": [
  C("What does Feser’s two-rocks parallel show about Leftow’s objection?", ["That arithmetic depends on rocks", "That water is not H₂O", "That a necessary truth can entail truths about something without depending on it in any interesting sense", "That God wills the laws of chemistry"], 2, "Entailment by contraposition is not dependence; hydrology will never overturn God.", "analyze"),
  C("Why does Feser say Leftow’s appeal to voluntarism fails?", ["Because voluntarism is scientifically disproven", "Because it begs the question against deity theorists, who reject voluntarism", "Because Leftow is not a voluntarist", "Because voluntarism supports Platonism"], 1, "Leftow can make the antecedent seem possible only by assuming God could have willed otherwise — exactly what deity theorists deny.", "understand"),
  C("Why does divine simplicity matter to this debate?", ["It means God’s ideas and God’s nature are really the same, so grounding truths in divine ideas grounds them in God’s nature", "It shows water is simple", "It makes God changeable", "It means God has no ideas at all"], 0, "Scholastic realism counts as a “deity theory” precisely because, in a simple God, intellect and nature are one.", "understand")
 ],
 "terms": ["Deity theory", "Voluntarism", "Divine simplicity", "Entailment", "Contraposition", "A posteriori necessity", "Necessary truth", "Antecedent and consequent"]
}

SEC[17] = {
 "body": "Another objection targets the very idea of a conceptually omniscient being. It seems to presuppose a *set of all truths*, and Patrick Grim argues there cannot be one. Suppose S is the set of all true propositions. By Cantor’s theorem, the power set of S (the set of all its subsets) has more members than S — and since (the thought runs) each subset generates a further truth, S cannot contain all truths after all. So there is no set of all truths — and, Grim says, no omniscience.\n\nFeser gives three replies. (1) Following Alvin Plantinga, the argument **proves too much**: the same reasoning shows there is no set of all propositions, true or false, yet we coherently say things about all propositions — that every proposition is true or false and none is both. So why can we not coherently say an omniscient being knows all true ones? (2) Following Keith Simmons, omniscience does not require a *set* of known truths: even if there is no such set, it does not follow that there is any particular proposition God fails to know — and that is all omniscience requires. (3) Following William Wainwright, Grim assumes God’s knowledge consists of many discrete ideas forming a set. But given **divine simplicity**, what we describe as God’s grasp of *all men are mortal*, his grasp of *Socrates is a man*, and so on are, in God, one and the same reality described in different ways.\n\nNotice that none of these replies disputes Cantor’s theorem itself. They dispute only the assumption that omniscience requires the truths to form a completed set.",
 "takeaway": "Cantor’s theorem at most shows the truths do not form a set; it does not show any truth is unknown to God — and God’s knowledge is not a set of discrete items anyway.",
 "deepDive": "Start with Cantor’s idea in miniature. Take a set with two members, {a, b}. Its subsets are: the empty set, {a}, {b}, and {a, b} — four subsets from two members. With three members you get eight subsets; with *n* members, 2ⁿ. Cantor proved something remarkable: the same holds for infinite sets. The collection of all subsets of any set is always strictly larger than the set.\n\nGrim applies this to truths. Suppose S is the set of all truths. For each subset of S there is a distinct truth about it (for example, that a given truth does or does not belong to that subset). So there are more truths than S contains — contradiction. Hence no set of all truths. Hence, he says, no omniscience.\n\nNow the replies, slowly.\n\n**Plantinga: it proves too much.** The same reasoning rules out a set of all *propositions*. Yet you can confidently assert, “Every proposition is either true or false.” That sentence talks about all propositions without needing them to form a set. If that is coherent, so is “God knows every true proposition.”\n\n**Simmons: no set is needed.** Omniscience can be stated without sets: *for any proposition p, if p is true, God knows p.* That is a universal claim, like “every human is mortal.” Showing that the truths don’t form a set does nothing to produce a *particular* truth God fails to know.\n\n**Wainwright: simplicity.** Grim pictures God’s mind as a vast filing cabinet, each file a separate idea, the whole forming a set. But divine simplicity denies that God’s knowledge is composed of separate items. What we distinguish, from our side, as many acts of knowing are in God one reality.\n\nA nuance: Feser does not challenge Cantor’s mathematics at all. The fight is over a philosophical assumption smuggled in — that knowing everything means possessing a completed collection.\n\nThis defends steps 22–25. The usual confusion is thinking “mathematics has refuted God.” What has actually been shown is a limit on *sets*; logicians routinely talk about “all propositions” or “all sets” without treating them as a set.",
 "checks": [
  C("What does Plantinga’s reply to Grim claim?", ["Cantor’s theorem is false", "God knows only finitely many truths", "Omniscience requires a set of all truths", "Grim’s reasoning would equally rule out a set of all propositions, yet we coherently make claims about all propositions"], 3, "If the argument worked, we could not say “every proposition is true or false,” but we can.", "understand"),
  C("According to Simmons’s reply, what does omniscience require?", ["A completed set of all truths", "That there be no particular true proposition God fails to know", "Knowledge of all sets", "That Cantor’s theorem be false"], 1, "Omniscience is a universal claim about propositions, not about possessing a set.", "understand"),
  C("Does Feser dispute Cantor’s theorem?", ["Yes — he argues it fails for infinite sets", "Yes — he says it is irrelevant to mathematics", "No — he disputes only the assumption that omniscience requires the truths to form a set", "No — he accepts Grim’s conclusion"], 2, "All three replies leave Cantor’s mathematics intact.", "analyze")
 ],
 "terms": ["Power set / Cantor’s theorem", "Set (and subset)", "Omniscience (unqualified)", "Conceptual omniscience", "Divine simplicity", "Proposition"]
}

SEC[18] = {
 "body": "The last criticism comes from within Scholasticism. Some Scholastics (Peter Coffey; also the Mercier *Manual*) hold that Scholastic realism is true but is not a basis for *proving* God — it is a doctrine to bring in only after God is established on other grounds. Coffey objects that the Augustinian argument presupposes that the possible is eternally and necessarily possible — that horses and unicorns (unlike round squares) were possible before any world or finite mind existed. How could we know this unless we already knew of a necessary intellect grounding it? He also suggests that the idea of an order of abstract objects independent of our minds is a cognitive illusion of the kind Platonism falls into.\n\nFeser finds this weak. First, even an **atheist** can agree that possibilities are eternal and necessary — he will interpret them in Platonic terms, which is exactly why one need *not* presuppose a divine intellect to accept the premise. Second, Coffey, being a Scholastic realist, cannot say such an order is wholly illusory, since he believes it exists in the divine intellect; only the Platonic interpretation of it could be illusory.\n\nRead charitably, Coffey poses a dilemma: whoever affirms a mind-independent order of abstract objects means either (a) a Platonic third realm — which is false — or (b) ideas in God — which is true but question-begging in a proof. Feser calls this a **false choice**. One can affirm that there is an order of abstract objects existing in *some* way independent of all finite minds while leaving open *what* way. That is precisely the common ground on which Platonists and Scholastics debate which view explains it best. Since the Augustinian can accept this thesis without affirming (a), he assumes nothing false; since he can accept it without affirming (b), he begs no question. So Coffey’s objection fails.",
 "takeaway": "The Augustinian argument starts from ground that Platonists and Scholastics share — an order of abstract objects independent of finite minds — so it neither assumes a falsehood nor begs the question.",
 "deepDive": "To see why Coffey’s objection fails, get clear on what **begging the question** is. An argument begs the question when one of its premises can only be accepted by someone who already accepts the conclusion. The test is simple: *could someone who rejects the conclusion reasonably accept the premise?*\n\nApply the test. The disputed premise is that possibilities are eternal and necessary — that horses and unicorns were possible before any world or finite mind existed. Who accepts that? Theists, yes. But also atheist Platonists, who believe possibilities are eternal features of a mindless abstract realm. Since people who reject God accept the premise, it does not presuppose God. Test passed.\n\nA detective analogy helps. “Someone was in the room at midnight” is a premise that does not name the culprit; the detective then eliminates suspects one by one. The Augustinian’s neutral premise is: *there is an order of abstract objects existing in some way independent of all finite minds.* It does not say how. Plato is one suspect (a third realm); God is another (divine ideas). Plato is then eliminated by separate arguments — inertness, animality, intentionality (step 10). No step assumes the answer in advance.\n\nNotice the charity in Feser’s treatment. Coffey is a fellow Scholastic realist; the dispute is not over whether Scholastic realism is true, but over whether it can serve as the *basis* of a proof. Feser also turns Coffey’s own view against the “illusion” charge: a Scholastic cannot call the order of eternal truths an illusion, because he believes it exists in God. What might be illusory is only the Platonic *interpretation* of that order.\n\nThis defends the starting points of the argument — especially the claim, used in steps 2, 5, and 12, that abstract objects do not depend on finite minds.\n\nThe usual confusion: thinking that because a premise is congenial to theists, it must beg the question. The correct test is whether non-theists can accept it on independent grounds. Here they visibly do — which is why Platonism is a live option in the first place.",
 "checks": [
  C("What is Feser’s first reply to Coffey?", ["Even an atheist Platonist can accept that possibilities are eternal and necessary, so the premise does not presuppose a divine intellect", "Possibilities are not eternal", "Coffey is not a Scholastic", "Unicorns are impossible"], 0, "A premise accepted by those who reject the conclusion does not beg the question.", "understand"),
  C("Why does Feser call Coffey’s dilemma a “false choice”?", ["Because Platonism is true", "Because Coffey misunderstands unicorns", "Because God’s existence is self-evident", "Because one can affirm an order of abstract objects independent of finite minds while leaving open whether it is Platonic or divine"], 3, "That neutral thesis is the common ground on which Platonists and Scholastics then argue.", "analyze")
 ],
 "terms": ["Scholastic realism", "Platonic realism", "Pure possibles", "Third realm", "Modality (possibility and necessity)", "Mind-independence", "Argument by elimination (disjunctive syllogism, modus tollens)", "Begging the question"]
}
