# Depth pass D: reading guide for Chapter 3 (printed pages)
GUIDE = {
 "beforeYouRead": "This chapter asks a question you have probably never asked, even though you rely on the answer every day: **what are things like numbers, meanings, and possibilities?** You know that 2 + 2 = 4. You know that “snow is white” means the same thing in English and German. You know Mars *could* have had three moons. But none of these is a physical object you can point to. So what are they, and where are they?\n\nFeser’s answer, drawn from Saint Augustine, is surprising: truths like these are *thoughts*, and because they are eternal and could not have been otherwise, they must be the thoughts of an eternal mind that could not fail to exist — God. Unlike the other proofs in the book, this one is not about causes or the beginning of the universe. It is about the nature of truth itself.\n\nWhat will you be asked to accept? Mainly things most people already believe: that math and logic are discovered rather than invented; that two people can think the same thought; that something was possible before anyone imagined it. Feser then argues that the popular alternatives — “it’s all just words,” “we made it up,” or “these things float in their own realm” — fall apart when examined.\n\nSome reassurance about the hard parts. The first fifteen pages move through an old debate with a lot of labels (realism, nominalism, conceptualism, Platonic, Aristotelian, Scholastic). Don’t try to memorize them on the first pass; use the map below and the vocabulary list, and focus on the *reasons* each view is accepted or rejected. The section on conceptualism and “psychologism” (pp. 94–97) and the objections at the end (pp. 110–116) are the densest; it is fine to read them twice. Stage 2 borrows one big idea from Chapter 1 — “pure actuality,” meaning having no unfulfilled capacities at all — so glance back at that if it has faded. You don’t need any math beyond simple arithmetic; even the section about Cantor’s theorem is explained below in plain terms.",
 "knowFirst": [
  {"term": "Universal", "plain": "A general feature many things can share, like redness or roundness. A red ball and a red fire truck both have redness."},
  {"term": "Abstract object", "plain": "Something we can think about and know truths about, but can’t see or touch — such as the number 7 or the meaning of a sentence."},
  {"term": "Proposition", "plain": "What a sentence means or claims, which can be true or false. The same proposition can be said in many languages."},
  {"term": "Possible world", "plain": "A complete way things could have been — for example, a world in which Mars has three moons. It is not a real other planet or universe."},
  {"term": "Necessary truth", "plain": "Something that couldn’t possibly have been false, like 2 + 2 = 4."},
  {"term": "Contingent", "plain": "Able to be otherwise or not to exist at all. You are contingent: you might never have been born."},
  {"term": "Realism (about abstract objects)", "plain": "The view that things like numbers and meanings are real, not physical, and not made up by humans."},
  {"term": "Nominalism", "plain": "The view that there are no general features at all — only individual things and the general words we use for them."},
  {"term": "Conceptualism", "plain": "The view that general features exist, but only as ideas that human minds construct."},
  {"term": "Pure actuality", "plain": "From Chapter 1: being completely “fulfilled,” with no unrealized capacity of any kind. Feser argues only God is like this."}
 ],
 "questionsToHold": [
  "Where, if anywhere, would 2 + 2 = 4 be true if there were no people and no physical universe?",
  "When you and a stranger think “snow is white,” are you thinking two thoughts or one?",
  "Can anything be “about” something else — represent it — without a mind involved?",
  "Was it possible for humans to exist before there were any humans? What made that true?",
  "Why can’t human minds, which come and go, be the final home of truths that can never change?",
  "Even if some eternal mind holds these truths, what more is needed to show it is God?",
  "For each objection at the end: is the critic disputing a premise, or the definition of a word?"
 ],
 "map": [
  {"pages": "87–90", "section": "Informal statement of the argument: Stage 1 (abstract objects)", "what": "The pool-hall example introduces universals; then propositions (“Snow is white” / “Schnee ist weiss”), numbers vs. numerals, and possible worlds. Each is shown to be knowable but not physical.", "difficulty": 1, "tip": "Easy and vivid — read at normal speed. Make sure you can explain why erasing every “2” wouldn’t change arithmetic."},
  {"pages": "90–92", "section": "Stage 1: realism vs. nominalism and conceptualism; direct arguments 1–6", "what": "Feser names the three positions and gives six arguments for realism: one over many, geometry, mathematics, propositions, science, and possible worlds.", "difficulty": 2, "tip": "Slow down on the definitions of the three positions. For each argument, ask: what feature of abstract objects rules out matter and human minds?"},
  {"pages": "92–94", "section": "Stage 1: arguments against nominalism (7–8)", "what": "Why “it’s just words” fails: Russell’s resemblance regress, and the point that the word “red” is itself a universal.", "difficulty": 2, "tip": "Read the regress twice, drawing the levels on paper. The type/token idea (one word, many utterances) is the key to argument 8."},
  {"pages": "94–97", "section": "Stage 1: arguments against conceptualism (9–10)", "what": "Shared concepts and communication; then Frege’s attack on psychologism, the relativist version, and the Kantian version with its dilemma.", "difficulty": 3, "tip": "The densest stretch of Stage 1. Separate “how did we come to think this way?” from “is what we think valid?” and the self-refutation will become clear."},
  {"pages": "97–99", "section": "Stage 1: Platonic realism and its problems", "what": "Plato’s third realm of Forms, then four objections: causal inertness, the Third Man, the animality problem, and trees reduced to mirror images.", "difficulty": 3, "tip": "The animality argument (pp. 98–99) is the one Feser leans on — reread it until you can state it in two sentences. The Third Man can be skimmed."},
  {"pages": "99–101", "section": "Stage 1: Aristotelian realism", "what": "Universals exist in things and, as abstract, only in minds; Oderberg’s squareness quotation; how essences ground possibility and necessity.", "difficulty": 2, "tip": "The key sentence is that nothing is both abstract and mind-independent. Underline it — the rest of the chapter depends on it."},
  {"pages": "101–102", "section": "Stage 1: where Aristotelian realism runs out; Scholastic realism", "what": "Four hard cases (a world possible when none exists, unicorns, truths without minds, necessary truths), then Scholastic realism and the Augustinian thesis of a divine intellect.", "difficulty": 2, "tip": "List the four hard cases in the margin. Notice that Scholastic realism agrees with Aristotle about minds and with Plato about something beyond us."},
  {"pages": "103–106", "section": "Informal statement of the argument: Stage 2", "what": "Why the ground must be a necessarily existing intellect (not human, alien, or angelic); the interlocking system; conceptual omniscience; then pure actuality yielding God’s attributes.", "difficulty": 3, "tip": "Slow down on p. 106, where pure actuality enters — review Chapter 1 if needed. Note the difference between “conceptual” and full omniscience."},
  {"pages": "106–109", "section": "Stage 2 (continued): Welty’s six conditions", "what": "Objectivity, necessity, intentionality, relevance, plenitude, simplicity — and the drawing of Socrates as a carpenter.", "difficulty": 2, "tip": "Make a small table of which condition favors which view. The relevance point about the drawing is the most original idea here."},
  {"pages": "109–110", "section": "A more formal statement of the argument", "what": "The whole argument in 29 numbered steps.", "difficulty": 2, "tip": "Don’t memorize — map it: steps 1–5 (realism), 6–15 (Scholastic realism), 16–29 (one mind, and it is God). Compare with the Argument section of this module."},
  {"pages": "110–112", "section": "Some objections rebutted: are divine ideas “concrete”?", "what": "The objection that ideas in God aren’t abstract, with Feser’s replies and a long footnote on two definitions of “abstract.”", "difficulty": 3, "tip": "Read the footnote carefully: the whole disagreement is about what “abstract” means."},
  {"pages": "112–114", "section": "Some objections rebutted: Leftow on “deity theories”", "what": "The water = H₂O objection, the two-rocks parallel, the impossible “if,” and voluntarism.", "difficulty": 3, "tip": "Keep one idea in view: logical connection is not dependence. The rocks example is your anchor."},
  {"pages": "114–115", "section": "Some objections rebutted: Grim’s Cantorian argument", "what": "Whether Cantor’s theorem rules out a set of all truths, and three replies (Plantinga, Simmons, Wainwright).", "difficulty": 3, "tip": "You don’t need set theory: remember that a set always has more subsets than members, then focus on the three replies."},
  {"pages": "115–116", "section": "Some objections rebutted: Coffey’s charge of begging the question", "what": "A fellow Scholastic’s claim that the argument assumes God, and Feser’s “false choice” reply.", "difficulty": 2, "tip": "Ask of the key premise: could an atheist accept it? Feser’s answer is yes — atheist Platonists do."}
 ],
 "afterReading": [
  "Without notes, name the four kinds of abstract object and give one example of each.",
  "Explain in two sentences each why nominalism and conceptualism fail.",
  "State the animality argument against Plato in your own words.",
  "List the four hard cases that finite minds can’t ground, and say why an angel wouldn’t do either.",
  "Explain why the eternal truths must be in one mind rather than a committee of minds.",
  "Trace how Feser gets from “a necessarily existing intellect” to God, naming the role of pure actuality.",
  "Pick one of the four objections at the end and give Feser’s reply in under a minute, out loud.",
  "Take the section checks in this module’s summary, then the full quiz, and reread any section where you miss a question."
 ]
}
