# Depth pass: example / challenge / answer for every argument step
STEPS = {
 1: ("Ask “Is redness real?” and there are three basic answers: no, there is only the word “red” (nominalism); yes, but only as a concept in our heads (conceptualism); yes, and it is not our invention (realism).",
     "There are other options — abstract objects as useful fictions, as brain processes, or as brute facts that fit none of these boxes.",
     "Each alternative lands in one of the three: fictionalism denies their reality, brain-process views make them particular products of human minds, and real, non-human-made “brute” abstract facts are simply a form of realism."),
 2: ("That 2 + 2 = 4 was true before any human existed, would survive the disappearance of the universe, and belongs to an infinite series no finite collection of things or ideas could match.",
     "Mathematical truths only seem necessary and objective because of how our minds are built.",
     "That is psychologism, which Feser argues refutes itself (step 4); and the geometry and mathematics arguments show we discover these truths rather than invent them, and cannot change them."),
 3: ("When you, I, and Socrates each say “red,” we utter three tokens of one word type — so even the nominalist’s preferred “general word” is a universal.",
     "The nominalist can take resemblance as a primitive relation needing no further analysis.",
     "A resemblance relation holding among countless different pairs is itself one thing shared by many — a universal — and if the nominalist denies that, Russell’s regress begins."),
 4: ("You and I, and people centuries dead, all think one and the same Pythagorean theorem — not private versions of it.",
     "Our concepts need only be similar enough to allow communication; they need not be literally the same.",
     "“Similar enough in which respect?” reintroduces a shared concept; and the conceptualist’s own arguments must use concepts and logic he expects others to grasp as objectively valid."),
 5: ("Having shown that nominalism and conceptualism collapse while realism is well supported, only realism remains.",
     "", ""),
 6: ("The number 7 could exist (a) as a Form in a realm apart from all minds, (b) only in groups of seven things and in the finite minds that abstract it, or (c) also as an idea in a necessary intellect.",
     "Why not a fourth option — abstract objects simply exist in the material world?",
     "As abstract, they cannot: material things are always particular, while universals are general, and many truths and possibilities hold whether or not the material world exists."),
 7: ("For the Platonist, triangularity exists as the Form of Triangle, in which every billiard rack and pyramid participates.",
     "Modern Platonists don’t talk about Forms or participation; they just say abstract objects exist.",
     "The label does not matter: any view on which abstract objects exist apart from both matter and every mind is a third-realm view and inherits its problems."),
 8: ("On this view humanness exists in Socrates and, as abstract, in the minds of those who think about humanity — and nowhere else.",
     "Aristotle himself believed in a divine intellect, so it is misleading to call a godless view “Aristotelian.”",
     "In the argument the label names a version of realism that stops at contingent minds; Scholastic realism is Aristotelian in spirit and differs only by adding a necessary intellect, so nothing hangs on Aristotle’s own theology."),
 9: ("The possibility of unicorns exists as an idea in God’s intellect, even though no unicorn ever exists and before any human imagined one.",
     "Isn’t this just Platonism with the Forms relocated inside God?",
     "No mindless realm remains: the abstract objects are God’s own understanding, not independent objects he consults, so the problems of inert, self-standing Forms do not arise."),
 10: ("A Form of Triangle that affects nothing could neither shape a billiard rack nor inform anyone’s mind about triangles.",
      "Knowledge of mathematics does not require causal contact, so causal inertness is no objection.",
      "Even granting that, an inert Form could not explain why particular things conform to it, and the animality problem shows that a universal cannot exist as an individual thing at all."),
 11: ("Since Platonic realism just is the third-realm claim, the failure of that claim is the failure of Platonic realism.",
      "", ""),
 12: ("Before any human existed, it was possible for humans to exist — a possibility that could not have depended on human minds.",
      "Possibilities are grounded in the powers and potentials of actual physical things, so no mind is needed.",
      "That fails where there are no physical things (the possibility of a world when none exists), for possibilities involving different physics, for pure possibles like unicorns, and for necessary truths, which cannot rest on contingent things."),
 13: ("Aristotelian realism, as defined in step 8, just is the contingent-minds-only claim, so its failure is Aristotelian realism’s failure.",
      "", ""),
 14: ("Like the one door left unlocked after the other two are shown to be locked: realism is true, it has three versions, and two have been eliminated.",
      "Perhaps there is an overlooked fourth version of realism.",
      "Step 6’s options are exhaustive: real abstract objects exist either apart from all minds (third realm) or in intellects, and intellects are either all contingent or include a necessary one."),
 15: ("The truth that 2 + 2 = 4 exists as grasped by a necessarily existing intellect, not merely in human minds that come and go.",
      "", ""),
 16: ("To grasp “all men are mortal” you must grasp humanness and mortality, and that proposition together with “Socrates is a man” entails “Socrates is mortal.”",
      "Some propositions have nothing to do with each other — “cats are four-legged” is logically irrelevant to rain in Cleveland.",
      "Even unrelated propositions stand in logical relations: they are consistent or inconsistent, their failure to entail each other is itself a logical fact, and they combine into compound propositions with definite truth values."),
 17: ("That “all men are mortal” and “Socrates is a man” together entail “Socrates is mortal” would hold whether or not any finite mind ever thought any of them.",
      "Why not a division of labor, with different necessary minds holding different clusters of truths?",
      "Any division leaves logical relations crossing the boundary — every proposition is consistent or inconsistent with every other — so some mind must grasp relations spanning the whole system, and that mind grasps it all."),
 18: ("The whole web of universals, propositions, and possibilities, with all their logical connections, exists in a necessary intellect.",
      "", ""),
 19: ("A human intellect exists only because potentials were actualized — conception, growth, ongoing bodily processes; a necessary intellect cannot depend on anything like that.",
      "Couldn’t something exist necessarily and still have unrealized potentials?",
      "If its existence presupposed any actualization of potential, it would exist only on that condition and so contingently; as Chapter 6 adds, anything composed of act and potency depends on their combination and so is not necessary."),
 20: ("Trees can differ by the sturdiness of their roots and squirrels by whether they have tails (Chapter 1’s examples), but a purely actual being has no material features and no privations to differ by.",
      "Two purely actual beings might differ merely numerically, without any differing feature.",
      "Things of the same kind are distinguished only by some individuating factor — matter, time, or a perfection one has and the other lacks — and pure actuality has none of these, so there is nothing to make two of them two."),
 21: ("The imagined “committee” of necessary minds collapses into a single necessary intellect.",
      "", ""),
 22: ("Such a mind grasps, for every number, whether it is odd or even, along with every possible essence — including unicornity — and every necessary truth.",
      "Grasping infinitely many truths is impossible, since Cantor’s theorem shows there is no set of all truths.",
      "Omniscience requires only that no truth goes unknown, not that truths form a set; the argument proves too much; and God’s knowledge is one simple act, not a collection (Plantinga, Simmons, Wainwright)."),
 23: ("The one necessary intellect understands all essences, possibilities, and necessary truths — Adams’s “conceptual omniscience.”",
      "", ""),
 24: ("A student who has not learned calculus has an unrealized potential to know it; a mind ignorant of any truth likewise has an unrealized potential.",
      "Knowing contingent facts would make God depend on the world, or change as the world changes.",
      "Feser’s point is only that ignorance is unactualized potential; since the actual is a subset of the possible, knowing all possibilities already includes the actual — and Chapter 6 explains that God knows the world as its cause, like an author knowing his story, not by observing it."),
 25: ("So the necessary intellect knows not only that 2 + 2 = 4 but also what you ate for breakfast this morning.",
      "", ""),
 26: ("As the source of all actualizing power, pure actuality is omnipotent; lacking every privation, it is perfectly good; unable to change, it is outside time and matter.",
      "Why should lacking potential make something good in any sense we care about?",
      "For Feser a thing is good to the degree it realizes its nature without privation — as a good painter has actualized the relevant skills — so what lacks all privation is good in the fullest sense (argued in Chapter 1 and developed in Chapter 6)."),
 27: ("There is exactly one necessary intellect, and it is purely actual, omniscient, omnipotent, perfectly good, immutable, immaterial, incorporeal, and eternal.",
      "", ""),
 28: ("This list of attributes is how Augustine, Anselm, Aquinas, Maimonides, and the classical tradition describe God.",
      "The God people pray to is personal and loving, not an abstract intellect.",
      "An intellect that also has will is personal in the classical sense (Chapter 6 treats God’s will and goodness), and the argument reaches the core attributes believers ascribe to God; further truths about God go beyond what natural theology alone establishes."),
 29: ("God exists as the one necessary mind in which the eternal truths are thought.",
      "", ""),
}
