import json, collections
P = r'C:\Users\mleet\Desktop\house\five-proofs-course\content\ch3.json'
d = json.load(open(P, encoding='utf-8'))

# ---------- 1. keyTerms: backfill origin / confuseWith ----------
back = {
 "Abstract object": ("From Latin abstrahere, “to draw away”: what the mind draws away from particulars. The contemporary label is from 20th-century analytic metaphysics.", "Imaginary object — a unicorn image is imaginary; triangularity is abstract but real and knowable, not made up."),
 "Universal": ("Latin universalis, “belonging to the whole”; the ancient “problem of universals” goes back to Plato and Aristotle and was named in the Middle Ages.", "Collection or set — a universal is not the group of red things but what each of them shares; the group could vanish and redness recur."),
 "Abstraction": ("Latin abstrahere, “to draw away from”; central to Aristotle’s and Aquinas’s account of how the intellect knows.", "Imagination — imagining forms a picture of one particular triangle; abstraction grasps triangularity itself, which cannot be pictured."),
 "Proposition": ("Latin propositio, “a setting forth”; the modern notion owes much to Frege, who called it a “thought” (Gedanke).", "Sentence — a sentence is a token in some language; the proposition is the language-independent content it expresses."),
 "Numeral vs. number": ("Latin numerus, “number”; numerals are the signs, a distinction stressed by Frege.", "Digit — a digit is one kind of numeral (0–9); neither a digit nor any numeral is the number itself."),
 "Possible world": ("The idea goes back to Leibniz (God surveys infinitely many possible worlds); the term was formalized in 20th-century modal logic (e.g., Kripke).", "Parallel universe or multiverse — those would be actual physical regions; a possible world is just a way things could have been."),
 "Pure possibles": ("Scholastic term (possibilia): things possible in themselves though never actual.", "Impossibilities — a unicorn is a pure possible; a round square is impossible and has no possible world at all."),
 "Necessary truth": ("Leibniz’s “truths of reason,” as opposed to contingent “truths of fact.”", "Certain or well-known truth — necessity is about whether it could have been false, not how sure we are of it."),
 "Realism (about abstract objects)": ("From Latin res, “thing”; in medieval debates “realists” held that universals are real things, not mere names.", "Realism about perception (the external world is real) — a different debate; one can be a realist about tables and a nominalist about redness."),
 "Nominalism": ("Latin nomen, “name”: universals are mere names. Associated historically with Roscelin and William of Ockham.", "Conceptualism — nominalism denies universals are real; conceptualism grants they are real but only as human mental constructs."),
 "Resemblance nominalism": ("A version of nominalism defended in modern times; Russell’s regress objection is in The Problems of Philosophy (1912), ch. 9.", "Realism about resemblance — once resemblance is admitted as a real shared relation, the nominalist has granted a universal."),
 "Type vs. token": ("Distinction coined by the American philosopher C. S. Peirce.", "Universal vs. particular in general — type/token is one instance of that contrast, applied to words and symbols."),
 "Conceptualism": ("Latin conceptus, “something conceived”; associated with medieval figures such as Abelard (on some readings) and modern thinkers influenced by Locke and Kant.", "Aristotelian realism — both say abstract universals exist in minds, but the Aristotelian also holds universals exist in things and are abstracted from them, not invented."),
 "Psychologism": ("German Psychologismus, a 19th-century term; attacked by Frege and Husserl.", "Psychology — the empirical study of mental processes is fine; psychologism is the philosophical claim that logic and math reduce to it."),
 "Platonic realism": ("Plato; “Form” translates Greek eidos or idea, “look” or “shape.” Participation translates methexis.", "Scholastic realism — both posit a reality beyond matter and finite minds, but for Plato it is a mindless realm of Forms, for the Scholastic a divine intellect."),
 "Third Man argument": ("From Plato’s Parmenides; the name (tritos anthrōpos, “third man”) comes from Aristotle’s discussion of it.", "Russell’s resemblance regress — the Third Man targets Platonic Forms; Russell’s regress targets nominalist resemblance."),
 "Causal inertness": ("A standard feature of abstract objects in contemporary metaphysics; the related worry about knowing them is often called Benacerraf’s problem (1973).", "Immutability — God is unchanging but not inert; he is the source of all causal power. Platonic Forms would be powerless."),
 "Aristotelian realism": ("Aristotle; often called “moderate realism” in the Scholastic tradition.", "Conceptualism — Aristotelian universals exist in extramental things; conceptualist universals exist only in human minds."),
 "Substance": ("Latin substantia, “that which stands under,” translating Greek ousia, “being.”", "Material stuff — in ordinary speech “substance” means a material; in Aristotelian metaphysics it means a thing existing in its own right, like a tree or a person."),
 "Scholastic realism": ("Latin scholasticus, “of the schools”: the philosophy of the medieval universities (Aquinas and others), drawing on Augustine for the divine-ideas thesis.", "Platonic realism — Scholastic realism denies any mindless third realm; the eternal truths are ideas in God."),
 "Argument from eternal truths": ("Augustine argues from unchanging truth to God in On Free Choice of the Will, book 2; Leibniz calls God’s understanding “the region of the eternal truths.”", "The design argument — this argument is not about order or fine-tuning in nature but about the status of necessary truths."),
 "Interlocking system": ("Emphasized by Leibniz (as discussed by Robert M. Adams).", "The coherence theory of truth — that is a theory of what makes beliefs true; the interlocking system is about the logical relations among abstract objects themselves."),
 "Conceptual omniscience": ("Robert Merrihew Adams, Leibniz: Determinist, Theist, Idealist (1994).", "Unqualified omniscience — conceptual omniscience covers essences, possibilities, and necessary truths; full omniscience adds all contingent truths."),
 "Pure actuality": ("Latin actus purus; rooted in Aristotle’s energeia (actuality) versus dunamis (potentiality).", "Inactivity or static being — pure actuality is the opposite of lacking activity: it lacks only unrealized potential."),
 "Deity theory": ("Brian Leftow’s label in God and Necessity (2012).", "Voluntarism — a deity theory grounds necessity in God’s nature; voluntarism grounds it in God’s free will, so it could have been otherwise."),
 "Voluntarism": ("Latin voluntas, “will.” Descartes held that God freely created the eternal truths; Leftow holds a version for some necessities.", "Deity theory in general — the Scholastic is a deity theorist but not a voluntarist: necessary truths flow from God’s intellect and nature, not arbitrary choice."),
 "Divine simplicity": ("Latin simplex, “single-fold”; classic statement in Aquinas, Summa Theologiae I, q. 3; discussed in Feser’s Chapter 2.", "Welty’s simplicity condition — that is a methodological rule against multiplying kinds of entity, not a claim that God lacks parts."),
 "Welty’s six conditions": ("Greg Welty, “Theistic Conceptual Realism,” in Beyond the Control of God? (ed. Paul Gould, 2014).", ""),
 "Truthmaker": ("A term from contemporary metaphysics (e.g., D. M. Armstrong).", "Truth-bearer — a truth-bearer (a proposition) is what is true; a truthmaker is what in reality makes it true."),
 "Power set / Cantor’s theorem": ("Georg Cantor (1891); Patrick Grim applied it against omniscience (1988).", "Subset — a subset is one collection drawn from a set; the power set is the collection of all such subsets."),
}
for k in d['keyTerms']:
    o, c = back.get(k['term'], ("", ""))
    k['origin'] = o
    k['confuseWith'] = c
missing_back = [k['term'] for k in d['keyTerms'] if k['term'] not in back]
print("no backfill for:", missing_back)

new_terms = [
 {"term": "Particular (instance)", "definition": "An individual concrete thing that exhibits a universal. Particulars are located in space and time and can be counted, destroyed, and replaced.", "example": "The eight ball on this table is a particular; its roundness is shared with the moon.", "origin": "Latin particularis, “concerning a part.”", "confuseWith": "Token — a token is a particular occurrence of a type (usually of a word or symbol); “particular” is the broader category."},
 {"term": "Instantiation (exemplification)", "definition": "The relation between a particular and a universal it has: the particular instantiates or exemplifies the universal.", "example": "A stop sign instantiates redness; a pyramid instantiates triangularity.", "origin": "Latin instantia, “presence”; exemplum, “sample.”", "confuseWith": "Participation — Plato’s term for how things relate to separately existing Forms; instantiation need not assume a third realm."},
 {"term": "Problem of universals", "definition": "The ancient question of whether general natures and properties are real, and if so, what kind of existence they have — in things, in minds, or in a separate realm.", "example": "Is redness something real that stop signs and strawberries share, or just a word we apply to both?", "origin": "Debated since Plato and Aristotle; named and intensely discussed in medieval philosophy (Boethius, Abelard, Ockham).", "confuseWith": ""},
 {"term": "One over many argument", "definition": "The argument that a single universal is present in many particulars and cannot be identified with any one of them or with their collection, since it would survive their destruction.", "example": "Destroy every triangle in existence; triangularity could still be instantiated in a new one tomorrow.", "origin": "A classic Platonic argument form; Feser gives it as the first direct argument for realism.", "confuseWith": "The Third Man argument — the one over many supports realism; the Third Man is an objection to the Platonic version of it."},
 {"term": "Form (Platonic) and participation", "definition": "For Plato, a Form is an eternal, unchanging, mind-independent exemplar of a kind or property; particular things are what they are by participating in and imperfectly resembling it.", "example": "The Form of Human Being, in which Socrates and every other man participate.", "origin": "Greek eidos or idea (“look,” “shape”); participation translates methexis.", "confuseWith": "Aristotelian (substantial) form — a principle within a thing that makes it what it is, not a separately existing exemplar."},
 {"term": "Third realm", "definition": "The Platonist’s domain of abstract objects that is neither physical nor mental, existing outside space, time, and all minds.", "example": "A mathematical Platonist might say the number 7 exists in a third realm, known but not located anywhere.", "origin": "Frege used the phrase for the realm of thoughts (propositions), distinct from the physical and the psychological.", "confuseWith": "The divine intellect — Scholastic realism agrees there is a reality beyond matter and finite minds but insists it is a mind."},
 {"term": "Essence (nature)", "definition": "What a thing is — the set of features that makes it the kind of thing it is and grounds what is possible, impossible, and necessary for it.", "example": "Human nature makes it possible to hold one’s breath for ten seconds but impossible for ten hours.", "origin": "Latin essentia, from esse, “to be”; translating Aristotle’s “what it is to be” (to ti ēn einai).", "confuseWith": "Existence — essence is what a thing is; existence is the fact that it is (the theme of Chapter 4)."},
 {"term": "Contingent", "definition": "Able to exist or not exist, or to be true or false; dependent on conditions that might not have obtained.", "example": "Human minds are contingent: once there were none, and there may be none again.", "origin": "Latin contingere, “to happen, to touch upon.”", "confuseWith": "Uncertain — a contingent truth can be known with certainty (Caesar was assassinated); it is contingent because it could have been otherwise."},
 {"term": "Uninstantiated universal", "definition": "A universal that no actual thing has, though it could be had.", "example": "Unicornity, centaur-ness, and mermaid-ness.", "origin": "", "confuseWith": "An impossible property — “round-squareness” cannot be instantiated at all; unicornity merely happens not to be."},
 {"term": "Modality (possibility and necessity)", "definition": "The ways in which something can be true: possibly, necessarily, contingently, or impossibly. The metaphysics of modality asks what grounds these facts.", "example": "It is possible Mars had three moons, necessary that 2 + 2 = 4, impossible that a square is round.", "origin": "Latin modus, “manner, mode.”", "confuseWith": "Physical possibility — logical/metaphysical possibility is constrained by logic, not by the actual laws of physics."},
 {"term": "Necessary existence (absolute necessity)", "definition": "Existing in such a way that it is impossible not to exist — not depending on anything else or on any potential being actualized.", "example": "Stage 2 argues that the intellect grounding necessary truths must exist necessarily, unlike humans or angels.", "origin": "Developed in Avicenna, Aquinas, and Leibniz; tied in Feser to pure actuality.", "confuseWith": "Everlasting existence — an angel may never cease to exist, yet it exists contingently because God might not have created it."},
 {"term": "Intentionality (Welty’s condition)", "definition": "The “aboutness” of abstract objects: like thoughts, they represent something beyond themselves.", "example": "The proposition that all men are mortal represents the state of affairs of all men being mortal.", "origin": "Latin intendere, “to aim at”; revived as a technical term by Brentano.", "confuseWith": "Intention in the sense of purpose — intentionality here is representation, not planning to do something."},
 {"term": "Plenitude and relevance conditions", "definition": "Two of Welty’s tests: plenitude requires enough abstract objects to do all the work they are posited for; relevance requires that they help explain why there are the necessary and possible truths there are.", "example": "Relevance: an idea in an omnipotent mind of Socrates as carpenter explains why he could have been one; a drawing does not.", "origin": "Greg Welty, “Theistic Conceptual Realism” (2014).", "confuseWith": "Simplicity condition — plenitude asks for enough entities; simplicity forbids more kinds than necessary."},
 {"term": "Theistic Conceptual Realism", "definition": "Greg Welty’s name for the view that abstract objects are thoughts in God’s mind — essentially what Feser calls Scholastic realism.", "example": "Welty argues this view best satisfies all six of his conditions.", "origin": "Greg Welty (2014).", "confuseWith": "Conceptualism in Feser’s sense — Welty’s “conceptualism” is broader and includes Aristotelian realism; Feser’s conceptualism means human-mind-made universals."},
 {"term": "Divine ideas", "definition": "The eternal exemplars of all possible things, truths, and essences as they exist in God’s intellect.", "example": "The possibility of a world with unicorns exists as a divine idea, whether or not God creates unicorns.", "origin": "Augustine (drawing on Neo-Platonism), later Aquinas and Leibniz.", "confuseWith": "Human concepts — our concepts are learned by abstraction and many; God’s ideas are eternal and, given simplicity, one reality."},
 {"term": "Omniscience (unqualified)", "definition": "Knowing all truths whatsoever — necessary and contingent, possible and actual.", "example": "God knows not only that 2 + 2 = 4 but what you ate for breakfast.", "origin": "Latin omnis, “all,” + scientia, “knowledge.”", "confuseWith": "Conceptual omniscience — which covers only essences, possibilities, and necessary truths."},
 {"term": "Entailment", "definition": "A logical relation in which the truth of some propositions guarantees the truth of another.", "example": "“All men are mortal” and “Socrates is a man” together entail “Socrates is mortal.”", "origin": "", "confuseWith": "Dependence — A can entail B (or be entailed by it) without depending on B, as arithmetic entails truths about rocks."},
 {"term": "Radical relativism", "definition": "The view that concepts, logic, mathematics, and science are all products of contingent biological, social, historical, and cultural forces, with no necessary connection to objective reality.", "example": "Claiming that logic is merely a Western cultural product that another society could replace.", "origin": "A development of psychologism, as Feser describes it.", "confuseWith": "Recognizing cultural influence on how truths are expressed — sentences differ across cultures; propositions and logical relations do not."},
 {"term": "Kantian conceptualism", "definition": "The less radical view, inspired by Kant, that our concepts and logic reflect only the structure of our minds rather than objective reality, but necessarily and unchangeably so.", "example": "Saying causality and number are forms our minds impose on experience, not features of things in themselves.", "origin": "Immanuel Kant (1724–1804), Critique of Pure Reason.", "confuseWith": "Radical relativism — the Kantian says our mental structure is fixed and universal, not culturally variable."},
 {"term": "Fictionalism (useful fictions)", "definition": "The view that talk of numbers and other abstract objects is literally false but useful, like a good story.", "example": "“2 + 2 = 4” is true in the story of arithmetic the way “Sherlock lives on Baker Street” is true in Conan Doyle.", "origin": "A modern position (e.g., Hartry Field); Feser mentions “useful fictions” among the options realism rejects.", "confuseWith": "Formalism — which treats mathematics as a game of manipulating symbols by rules; both deny mathematical objects exist."},
 {"term": "Angel (created pure intellect)", "definition": "In traditional theology, a disembodied intellect that does not perish but exists only because God creates it.", "example": "Feser uses a world containing only angels as a possible world with no matter or human minds.", "origin": "Greek angelos, “messenger.”", "confuseWith": "A necessary being — an angel never dies but still exists contingently, so it cannot ground necessary truths."}
]
d['keyTerms'].extend(new_terms)

# ---------- 2. quiz ----------
Q = lambda q, o, a, e, l: {"q": q, "options": o, "answer": a, "explanation": e, "level": l}
new_quiz = [
 Q("In Feser’s formal argument, which step secures that there is only one necessarily existing intellect?",
   ["Step 16, that abstract objects form an interlocking system", "Step 21, drawn from steps 19–20 (a necessary intellect is purely actual, and only one thing can be purely actual)", "Step 14, that Scholastic realism is true", "Step 28, that such a being is God"], 1,
   "The interlocking system rules out a division of labor informally, but in the numbered argument uniqueness is step 21, inferred from steps 19 and 20. Step 14 only yields at least one necessary intellect.", "analyze"),
 Q("Which premise of the formal argument imports Chapter 1’s result that what is purely actual is omnipotent, fully good, immutable, immaterial, incorporeal, and eternal?",
   ["Step 2", "Step 10", "Step 17", "Step 26"], 3,
   "Step 26 brings in the attributes of pure actuality established in Chapter 1; step 20 (uniqueness) also relies on Chapter 1.", "recall"),
 Q("A friend says: “Math is just a social convention, like driving on the right.” Which of Feser’s arguments answers this most directly?",
   ["The arguments from geometry and mathematics: these truths are discovered, unalterable, and were true before any human existed", "The Third Man argument", "Grim’s Cantorian argument", "Welty’s simplicity condition"], 0,
   "A convention could have been otherwise and depends on us; mathematical truths are necessary, discovered, and independent of human minds. The Third Man concerns Platonism, not conventionalism.", "apply"),
 Q("What would Feser say to someone who claims that triangularity is just a pattern of neurons in the brain?",
   ["He would agree, provided the neurons are in God’s brain", "He would say neurons are themselves Platonic Forms", "He would note that triangularity is instantiated when no one is aware of it, survives the destruction of instances, and is shared by many minds, so it cannot be a brain process", "He would say neurons are causally inert"], 2,
   "Brain processes are particular, contingent, and private; triangularity is universal, necessary in its truths, and shared. Feser lists “brain processes” among the answers realism rejects.", "understand"),
 Q("Which distinction does the objection “divine ideas would be concrete, not abstract” ignore?",
   ["Per se versus per accidens causal series", "Sentence versus proposition", "The Scholastic, abstraction-based sense of “abstract” versus the contemporary outside-space-and-time sense", "Conceptual versus unqualified omniscience"], 2,
   "The objection presupposes the contemporary definition. For Aristotelians and Scholastics, “abstract” is defined by the intellect’s act of abstraction, so abstract objects exist only in intellects.", "analyze"),
 Q("According to Feser, what distinction does Leftow’s water objection blur?",
   ["Logical entailment versus genuine dependence", "Type versus token", "Numeral versus number", "Platonic versus Aristotelian realism"], 0,
   "That the divine nature entails necessary truths about water no more makes God depend on water than arithmetic’s entailing truths about rocks makes it depend on rocks.", "analyze"),
 Q("Why does Feser think the argument from science supports realism?",
   ["Because most scientists are realists", "Because science proves God’s existence directly", "Because laboratory instruments detect universals", "Because scientific laws and classifications are general, so they refer to universals, and science aims at mind-independent facts while using mathematics"], 3,
   "The argument is about what accepting science commits one to: mind-independent universals and mathematical objects. It is not an appeal to scientists’ opinions.", "understand"),
 Q("Which examples does Feser give of “pure possibles”?",
   ["Round squares and married bachelors", "Unicorns, centaurs, and mermaids", "Mars’s two moons", "The Andromeda galaxy and the Milky Way"], 1,
   "Pure possibles are possible but never actual. Round squares are impossible; Mars’s moons and the galaxies are actual.", "recall"),
 Q("Why is there no possible world in which 2 + 2 = 5?",
   ["Because the laws of physics forbid it", "Because humans cannot imagine it", "Because God chose not to create such a world", "Because it is self-contradictory, and possibility in this sense is limited by logic rather than physics"], 3,
   "Feser notes that possible worlds are not constrained by physical laws (physicists consider different ones) but are constrained by logic. Option 3 would be voluntarism.", "understand"),
 Q("A student insists: “When you say ‘red’ and I say ‘red,’ we utter different words that merely look alike.” What follows, according to Feser?",
   ["Nominalism is vindicated", "No one would ever use the same word twice, communication would be impossible, and the appeal to resemblance reopens the regress", "Words turn out to be Platonic Forms", "Conceptualism follows automatically"], 1,
   "This is the nominalist’s escape from the “words are universals too” problem, and Feser argues it is absurd on its face, destroys communication, and revives Russell’s regress.", "apply"),
 Q("What does the architect-and-pyramid example show about Platonic realism?",
   ["Triangularity has effects when it exists in material things or minds, but a Form existing in neither would seem causally inert", "Architects intuit Forms directly", "Pyramids participate in the Form of Pyramid", "Concepts are really material things"], 0,
   "The architect’s concept of triangularity shapes the pyramid; a rack shapes the balls. A Form in no thing and no mind has no evident way to affect anything — including our knowledge.", "understand"),
 Q("Why is Aristotelian realism not a form of conceptualism?",
   ["Because it denies that universals exist", "Because it places universals in a third realm", "Because it holds universals exist in extramental things themselves, and the mind abstracts them rather than inventing them", "Because it holds universals exist only in God"], 2,
   "Both views say universals-as-abstract exist in minds, but only the Aristotelian says they also exist (concretely) in things. Option 4 is Scholastic realism.", "analyze"),
 Q("Before any human existed, was it possible for humans to exist? How does Feser use this?",
   ["Yes — and that possibility could not have depended on human minds or on anything then existing, so contingent minds cannot ground it", "No — possibility began when humans did", "Yes — and it was grounded in human DNA", "It is irrelevant because possibilities are fictions"], 0,
   "This appears in the argument from possible worlds and again as a hard case for Aristotelian realism limited to finite minds.", "apply"),
 Q("What would Feser reply to: “Why not say eternal truths depend on an eternal collection of many necessary minds?”",
   ["Collections of minds cannot think", "Angels are material, so they cannot be necessary", "Welty’s plenitude condition forbids more than one mind", "The truths form an interlocking system that must be grasped as a whole, and a necessary intellect is purely actual, of which there can be only one"], 3,
   "Both the interlocking-system argument and the uniqueness of pure actuality rule out a committee.", "analyze"),
 Q("Welty’s intentionality condition favors locating abstract objects in minds because:",
   ["Minds are simpler than Forms", "Minds always exist necessarily", "Abstract objects represent things, as thoughts do, and it is easier to see how they could have representational content in an intellect than in a third realm", "Intentions are acts of the will"], 2,
   "Intentionality is representational “aboutness.” Simplicity is a separate condition; and finite minds are not necessary.", "understand"),
 Q("Feser says the thesis that abstract objects exist in a divine intellect is famously associated with which thinker, and was also defended by whom?",
   ["Plato; Kant", "Augustine; Leibniz", "Frege; Russell", "Aristotle; Hume"], 1,
   "The argument from eternal truths is historically Augustinian and was defended by Leibniz. Plato held the third-realm view; Frege and Russell appear as critics of psychologism and nominalism.", "recall"),
 Q("In replying to Leftow, what does Feser say is the proper response to “Let’s consider a scenario where 2 + 2 doesn’t necessarily make 4”?",
   ["Consider it carefully to see what follows", "Deny that there could be any such scenario to consider", "Say that it depends on what God wills", "Appeal to Cantor’s theorem"], 1,
   "An impossible antecedent describes no scenario. Likewise the deity theorist need not entertain “if water were not necessarily H₂O.” Option 3 is Leftow’s voluntarism.", "understand"),
 Q("A skeptic says: “Your necessary mind knows math, like a textbook, but it doesn’t know my life.” Which step answers this?",
   ["Step 5", "Step 16", "Steps 24–25: lacking knowledge of contingent truths would be an unactualized potential, so a purely actual mind knows them", "Step 1"], 2,
   "Steps 24–25 move from conceptual to unqualified omniscience via pure actuality (step 19).", "apply"),
 Q("Why does Feser treat the Third Man as less decisive than the animality problem?",
   ["Because Aristotle definitively refuted it", "Because it targets nominalism, not Platonism", "Because it applies only to numbers", "Because its force has been disputed for millennia, whereas the animality problem shows directly that a universal cannot exist as an individual thing"], 3,
   "Feser mentions that Plato raised the Third Man himself and that its force is contested, then calls the animality objection “more telling.”", "understand"),
 Q("Coffey says the Augustinian argument presupposes that possibilities are eternal and necessary. What is Feser’s first reply?",
   ["Even an atheist Platonist can agree with this, so it does not presuppose a divine intellect", "Possibilities are not in fact eternal", "Coffey is really a nominalist", "Divine simplicity makes the question meaningless"], 0,
   "The premise is shared ground between Platonists and Scholastics, so accepting it does not beg the question. Feser then adds the false-choice point.", "analyze")
]
d['quiz'].extend(new_quiz)

# ---------- 3. shortAnswer ----------
d['shortAnswer'].extend([
 {"q": "Explain the argument from the nature of propositions, including Feser’s example of the proposition that there is no material world and no human mind.",
  "model": "Propositions cannot depend on the material world or on human minds. Necessary propositions like 2 + 2 = 4 would remain true if neither existed. Even many contingent ones would: that Caesar was assassinated on the Ides of March would stay true if everything material and every human mind vanished tomorrow. Most strikingly, if there had never been a material world or any human mind, the proposition that there is no material world and no human mind would have been true. A proposition that is true precisely when there is no matter and no human mind cannot be material or depend on human minds. (Feser points to Plantinga for further difficulties with identifying propositions with anything material or mental.)",
  "rubric": ["Covers necessary propositions", "Covers contingent propositions such as the Caesar example", "Explains the “no world, no mind” proposition and why it is decisive", "Concludes propositions depend on neither matter nor human minds"]},
 {"q": "Describe Welty’s six conditions and explain which view each favors.",
  "model": "Objectivity (abstract objects are independent of human minds) favors realism over nominalism and conceptualism. Intentionality (they represent, like thoughts) favors locating them in intellects rather than a third realm. Simplicity (no needless kinds of entity) favors two realms — matter and intellects — over the Platonist’s three. Necessity (they exist necessarily) and plenitude (there are enough of them, including many never thought by humans) rule out finite minds alone, favoring Scholastic over merely Aristotelian realism. Relevance (explaining why the necessary and possible truths are what they are) favors the divine intellect: a possible world as an idea in an omnipotent creator’s mind explains why it is possible, as a drawing or a third-realm entity cannot. Welty calls the winning view Theistic Conceptual Realism, essentially Feser’s Scholastic realism.",
  "rubric": ["Names all six conditions", "Links objectivity to realism", "Links intentionality and simplicity to minds over a third realm", "Links necessity and plenitude to Scholastic over Aristotelian realism", "Explains relevance with the Socrates-the-carpenter example"]},
 {"q": "Why must a necessarily existing intellect be purely actual, and why is this step so important for the argument?",
  "model": "If an intellect’s existence presupposed the actualization of some potential, it would exist only on condition that the potential be actualized — that is, contingently. So an intellect that exists with absolute necessity can have no such dependence: it must be purely actual. This step is the bridge to Chapter 1, which showed that what is purely actual is unique, omnipotent, perfectly good, immutable, immaterial, incorporeal, and eternal. It also yields full omniscience, since ignorance of any truth would be an unactualized potential. Without this step the argument would reach only a “conceptually omniscient” mind that a skeptic might deny is God; with it, the argument reaches the God of classical theism and converges with the other proofs.",
  "rubric": ["Explains why necessity rules out dependence on actualized potential", "Connects explicitly to Chapter 1", "Lists attributes that follow", "Explains how it yields full omniscience", "Explains its role in answering the “that’s not God” worry"]},
 {"q": "Explain the argument from the nature of possible worlds and why it is hard for any view that grounds possibility only in actual things and finite minds.",
  "model": "Much of what is possible has nothing to do with the actual world or human minds. There are possible worlds with radically different physical laws, including ones where humans could not exist; such possibilities cannot depend on the actual world, governed by actual laws, or on us. Before the material world or any human mind existed, it was possible for them to exist, and that possibility could not depend on things that did not yet exist. And there are possible worlds with no matter and no human minds at all, such as a world of only angels. The same points reappear as hard cases for Aristotelian realism: if nothing material or human had ever existed, there would be no essences in things and no abstracting minds to ground the possibility of a world; and pure possibles like unicorns are possible without instances and prior to anyone’s imagining them.",
  "rubric": ["Gives the different-physics case", "Gives the possibility-before-existence case", "Gives the no-matter-no-minds world", "Connects to the hard cases for Aristotelian realism (including pure possibles)"]},
 {"q": "Why is the Augustinian proof described as non-causal, and what practical difference does that make when presenting it?",
  "model": "The other four proofs reason from features of concrete things — change, composition, the essence/existence distinction, the need for explanation — to their cause. The Augustinian proof instead begins with abstract objects and asks what kind of existence necessary, eternal, representational truths could have; its answer is that they exist as ideas in a necessary intellect. It never claims that something caused 2 + 2 = 4. Practically, this means objections aimed at causal reasoning — “What caused God?”, worries about infinite causal regresses — do not touch it (Feser notes this later in the book). It also means it cannot supply everything the causal proofs do (Feser remarks that it does not by itself present God as the source of all causal power). When presenting it, you should frame it as a question about the status of truth, not about origins, and then show via pure actuality that it converges on the same God as the causal proofs.",
  "rubric": ["Contrasts its starting point with the four causal proofs", "States the question it actually asks", "Notes that “What caused God?” is irrelevant to it", "Notes how it converges with the other proofs via pure actuality", "Gives presentation advice"]}
])

# ---------- 4. flashcards ----------
F = lambda f, b: {"front": f, "back": b}
d['flashcards'].extend([
 F("Step 1: what does it claim and why?", "There are only three accounts of abstract objects — realism, nominalism, conceptualism — because they are either unreal, real but human-made, or real and not human-made."),
 F("Step 5: what follows and from what?", "Some version of realism is true — from steps 1–4 (three options; two refuted; one supported)."),
 F("Step 6: the three versions of realism", "Platonic (third realm), Aristotelian (things + contingent minds only), Scholastic (also a necessary mind)."),
 F("Step 10: what does it claim and why?", "The third-realm view faces insuperable objections: inertness, the Third Man, the animality problem, natures exiled from things."),
 F("Step 12: what does it claim and why?", "The contingent-minds-only view fails: pure possibles, possibility with no world, truths without minds, and necessary truths cannot depend on contingent minds."),
 F("Steps 14–15: what follows?", "Scholastic realism is true (from 5, 6, 11, 13), so abstract objects exist in at least one necessarily existing intellect (with 9)."),
 F("Step 16: what does it claim?", "Abstract objects are logically related so as to form one interlocking system of ideas."),
 F("Step 17: what does it claim and why?", "The reasons that put some abstract objects in a necessary intellect put the whole system there — the logical relations also hold independently of any world or finite mind."),
 F("Step 19: what does it claim and why?", "A necessarily existing intellect is purely actual; otherwise its existence would depend on some potential being actualized."),
 F("Step 20: what does it claim and where is it defended?", "There cannot be more than one purely actual being — defended in Chapter 1 (nothing could differentiate two)."),
 F("Step 22: what does it claim?", "An intellect containing the whole infinite system would be conceptually omniscient."),
 F("Step 24: what does it claim?", "If the necessary intellect didn’t know every contingent truth, it would have unrealized potential and not be purely actual."),
 F("Step 26: what does it claim?", "Whatever is purely actual is also omnipotent, fully good, immutable, immaterial, incorporeal, and eternal (Chapter 1)."),
 F("Step 28: what does it claim?", "For such a being to exist is just what it is for God to exist."),
 F("Why is the number of abstract objects infinite? (Feser’s example)", "For every number there is a true and a false proposition about whether it is odd or even, and each is consistent or inconsistent with every other proposition."),
 F("Logical relations Feser lists among propositions", "Entailment (all men mortal + Socrates a man → Socrates mortal), non-entailment (all men mortal + cats four-legged does not yield “raining in Cleveland”), consistency/inconsistency, and truth-functional compounds."),
 F("Socrates and Obama — what do they illustrate?", "Two people, in Greek and in English, 2,500 years apart, thinking one and the same proposition: that snow is white."),
 F("Which examples illustrate possible worlds?", "Romney winning in 2012; Mars with three moons (or one); different physics and no galaxies; unicorns with or without horses."),
 F("Aristotelian account of necessity: Feser’s examples", "A man can hold his breath 10 seconds, not 10 hours; once dead he can’t be revived naturally; 2 men + 2 men = 4 men, not 20."),
 F("Entailment vs. dependence", "Entailment: a logical relation that runs both ways by contraposition. Dependence: one thing holds because of another. Leftow confuses them."),
 F("Contemporary vs. Scholastic sense of “abstract”", "Contemporary: outside space and time, either abstract or concrete. Scholastic: produced by abstraction; the same nature is concrete in things, abstract in a mind."),
 F("How does divine simplicity figure in this chapter?", "It makes grounding truths in divine ideas the same as grounding them in God’s nature (Leftow), and it means God’s knowledge is not a set of discrete ideas (Grim)."),
 F("Voluntarism — and why it doesn’t save Leftow’s objection", "The view that necessities hold because God wills them. Assuming it begs the question against deity theorists, who reject it."),
 F("Why is “What caused God?” irrelevant to this proof?", "Because the Augustinian proof is not a causal argument; it reasons from the status of necessary truths, not from effects to a cause."),
 F("What does Scholastic realism grant to Plato, and what to Aristotle?", "To Aristotle: universals exist only in things or intellects — no mindless third realm. To Plato: there must be a reality beyond matter and finite minds (God’s intellect)."),
 F("Frege’s role in the chapter", "He opposed psychologism, defending the objectivity of logic and mathematics; the objectivity-of-concepts argument is associated with him.")
])

# ---------- 5. misconceptions ----------
d['misconceptions'].extend([
 {"myth": "Feser treats the Third Man as the knockout objection to Plato.", "correction": "He notes its force has been disputed for millennia and calls the animality problem more telling: a universal must be neither rational nor nonrational, but no individual can be."},
 {"myth": "Conceptual omniscience is the same thing as full omniscience.", "correction": "Conceptual omniscience covers essences, possibilities, and necessary truths. Feser needs a further step — pure actuality rules out the potential to know more — to get knowledge of all contingent truths."},
 {"myth": "Scholastic realism denies that universals exist in things or in human minds.", "correction": "It affirms both: universals exist concretely in things and abstractly in human and other finite intellects (step 9). It adds that they also, and ultimately, exist in a necessary divine intellect."}
])

json.dump(d, open(P, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)

d = json.load(open(P, encoding='utf-8'))
q = d['quiz']
nonrecall = sum(1 for x in q if x['level'] != 'recall')
print("keyTerms", len(d['keyTerms']), "quiz", len(q), collections.Counter(x['answer'] for x in q), "nonrecall%", round(100*nonrecall/len(q)))
print("shortAnswer", len(d['shortAnswer']), "flashcards", len(d['flashcards']), "misconceptions", len(d['misconceptions']),
      "socratic", len(d['persuade']['socratic']), "illustrations", len(d['illustrations']), "distinctions", len(d['distinctions']))
assert all(k.get('origin') is not None and k.get('confuseWith') is not None and k.get('example') for k in d['keyTerms'])
assert all(len(x['options']) == 4 and 0 <= x['answer'] <= 3 and x['explanation'] for x in q)
assert all(3 <= len(s['rubric']) <= 5 for s in d['shortAnswer']), [len(s['rubric']) for s in d['shortAnswer']]
print(len(set(k['term'] for k in d['keyTerms'])), "unique terms")
