import json
p = r'C:\Users\mleet\Desktop\house\five-proofs-course\content\_parts\ch3\p1.json'
d = json.load(open(p, encoding='utf-8'))
S = {s['heading']: s for s in d['summary']}
def setb(prefix, body):
    for h, s in S.items():
        if h.startswith(prefix):
            s['body'] = body; return
    raise KeyError(prefix)

setb("Three more kinds", "**Propositions** are what sentences express: true-or-false claims distinct from the sentences stating them. “John is a bachelor” and “John is an unmarried man” express one proposition; so do “Snow is white” and the German “Schnee ist weiss.” What a mind entertains in thinking is a proposition, not a string of words — which is why Socrates in fifth-century B.C. Athens and Barack Obama in twenty-first-century Washington can think exactly the same thing in different languages. You can see and erase a written sentence, but not the proposition: wipe out every token of that sentence in every language and it would still be true that snow is white.\n\n**Numbers** are likewise not their numerals. “2” is no more the number two than “II” is — or than the name “Barack Obama” is the man. Erasing every numeral would not make 2 + 2 = 4 false.\n\n**Possible worlds** are ways things could have been: Romney winning in 2012, Mars with three moons or one, different physical laws and no galaxies, unicorns alongside horses. Possibility here is limited by logic, not physics (physicists themselves consider alternative laws), so there is no possible world where 2 + 2 = 5 or round squares exist. We reason about possible worlds but cannot visit or perceive them.")

setb("Six direct arguments", "1. **One over many.** Triangularity and redness are not any particular triangle or red thing, nor the whole collection of them: all could be destroyed and the universal instantiated again. They are also instantiated when no human is aware of it. So they are neither material things, collections of them, nor mind-dependent.\n2. **Geometry.** Geometry discovers objective, necessary truths about perfect lines, angles, and circles (e.g., the angle sum of a Euclidean triangle). We found them, cannot change them, and they held before humans and would hold after us — and whatever happened to the material world, which in any case contains nothing geometrically perfect.\n3. **Mathematics in general.** Mathematical truths are necessary and unchanging; the world and human minds are contingent and changing. 2 + 2 = 4 was true before anyone noticed and would survive humanity’s forgetting or the universe’s disappearance. And the number series is **infinite**, while material things and human ideas are finite.\n4. **Propositions.** Necessary propositions would be true with no world and no minds — and so would many contingent ones: Caesar’s assassination on the Ides of March would stay true if everything vanished tomorrow. Had nothing material or human ever existed, the proposition *that there is no material world or human mind* would have been true. (Feser cites Plantinga for further problems.)\n5. **Science.** Scientific laws and classifications are general, so they refer to universals; science seeks mind-independent facts and is written in mathematics. Accepting science means accepting mind-independent abstract objects.\n6. **Possible worlds.** Many possibilities are independent of the actual world and of us: worlds with radically different physics, even ones where humans could not exist; the possibility of a world and minds before either existed; worlds with no matter or human minds at all (say, only angels).")

setb("Why nominalism fails", "Nominalism says there are only general *names* — the word “red,” but no redness. Yet why do we apply “red” to just these things? The natural answer, “because they have redness,” restores universals. Saying they simply *resemble* one another (in no specified respect) is implausible — surely they resemble each other *in redness* — and faces two further problems.\n\n7. **The vicious regress problem.** As Russell noted, resemblance is itself a universal: the stop sign/fire truck pair and the grass/Incredible Hulk pair are instances of one thing, resemblance. Say these resemblances merely resemble each other, and you have a higher-order resemblance — another universal — and so on without end.\n8. **The “words are universals too” problem.** The word “red” is itself a universal: your, my, and Socrates’ utterances are tokens of one word **type**. That is exactly the one-over-many situation nominalism denies — and the only reason the view seemed plausible. Say instead that the utterances are merely resembling words, and nobody ever uses the same word twice, even talking to themselves; communication becomes impossible (so why is the nominalist talking to us?), and the regress returns.\n\nIn general, nominalism is notoriously hard to state without smuggling universals in through the back door, which makes it self-undermining.")

setb("Why conceptualism fails", "Conceptualism tries a middle way: universals exist, but only in human minds. It too faces what are widely seen as insuperable difficulties.\n\n9. **The objectivity of concepts and knowledge.** When you and I think of redness, or of the Pythagorean theorem, we entertain *one and the same* concept and truth, not private versions — and share them with the dead, the unborn, and any new intelligent beings who might arise after humanity. So they have a foundation outside the human mind. **Communication** shows the same: if concepts were private constructs, your idea of snow and mine would never coincide and we could never mean the same thing — not even to agree or disagree about conceptualism.\n10. **The incoherence of psychologism.** Frege opposed **psychologism**, which reduces the laws of logic and math to psychological laws of how our minds operate. Add that our minds are shaped by contingent biological, social, and cultural forces, and you get radical relativism. But explaining *how* those forces shaped us requires universals (selection pressures, class interests, mutations, social trends), scientific and mathematical principles, and logic — the very things declared non-objective and nonexistent before our minds.\n\nThe milder **Kantian** version says our concepts reflect our minds’ structure, but necessarily so. Its defender faces a dilemma: if his concepts and logic have no objective validity, he cannot defend his view; if they give him objective knowledge of how our minds are, he has contradicted his view in defending it.")

setb("Three kinds of realism", "So some realism is true — but which: **Platonic**, **Aristotelian**, or **Scholastic**?\n\n**Platonic realism** (Plato first formulated a version) concludes that abstract objects, depending on neither matter nor human minds, inhabit a *third realm*, neither material nor mental: the Forms, outside space and time, in which particulars “participate” and which they imperfectly “resemble.” On some versions numbers, propositions, and possible worlds are treated the same way. Feser raises several problems:\n\n- **Causal inertness.** A rack arranges balls; a bell makes a sound; an architect’s *concept* of triangularity shapes his pyramid. But triangularity in no thing and no mind seems causally powerless. Then it cannot affect us (so how do we know it?) or particular triangles (so how does it explain their shape?).\n- **The Third Man.** A Form seems both universal and an individual thing, so the Form of Man and individual men would need a Super-Form, then a Super-Super-Form, endlessly. Plato raised this himself; its force is disputed.\n- **The animality problem** (more telling, Feser thinks). Animality must apply to rational and nonrational animals alike, so it can include neither and in itself is neither. But no individual can be neither rational nor nonrational. So animality cannot be an individual thing in its own right — a Form.\n- **Essences outside things.** If treeness is in the Form rather than the tree, a real tree is no more genuinely treelike than a statue or mirror image of one — absurd, especially for the Aristotelian, who regards trees and humans as **substances** with an intrinsic source of their properties and activities.")

setb("Welty’s six conditions", "Feser notes that Greg Welty defends a very similar view, **Theistic Conceptual Realism** (terminology aside — Welty’s “conceptualism” includes Aristotelian realism — it is essentially Scholastic realism). Welty’s six conditions for an adequate theory: **objectivity** (independence of human minds), **necessity**, **intentionality** (abstract objects *represent*, as thoughts do), **relevance** (explaining why there are the necessary and possible truths there are), **plenitude** (enough abstract objects for their work), and **simplicity** (no needless kinds of entity).\n\nObjectivity requires realism. Intentionality favors minds over a third realm, since representation is intelligible in an intellect. Simplicity favors two realms (matter and intellects) over three. Necessity and plenitude favor Scholastic over merely Aristotelian realism, since finite minds are contingent and countless abstract objects were never entertained by humans. Relevance does too: a drawing of Socrates hammering nails (Welty’s example) represents his possibly being a carpenter, but no one thinks he could not have been one had the drawing not existed — and a third-realm possible world is no better. For the Scholastic, a possible world is an idea in an omniscient, omnipotent cause who could have created that world by it; God’s intellect, will, and power make abstract objects relevant to what can happen.")

setb("Objection 1", "Feser notes the debate is over 2,300 years old and cannot be fully canvassed, then answers objections aimed at Scholastic realism specifically. Some critics (Yandell and Craig, replying to Welty) say ideas in God’s mind would be concrete, not abstract. Feser replies that there is no consensus on what abstract objects are, and that the objection begs the question anyway: for Aristotelians and Scholastics, an abstract object just *is* what an intellect forms by abstracting, so it can exist *only* in an intellect. A footnote locates the deeper clash: moderns treat thoughts as concrete mental states and draw the abstract/concrete line by space and time; Scholastics treat thinking as receiving a form without its matter, so the same nature can exist concretely in things and abstractly in a mind.")

setb("Objection 2", "Brian Leftow objects to “deity theories,” which ground necessity in God’s nature (as Scholastic realism does, since in a simple God intellect and nature are one). If water = H₂O is necessary and follows from God’s nature, then were it not necessary, God would not exist — so God “depends” on water. Feser’s parallel: 2 + 2 = 4 entails that two rocks plus two rocks make four, yet arithmetic does not depend on rocks; entailment is not dependence, and neither mineralogy nor hydrology will overturn necessary truths. Leftow does not claim hydrology could falsify God, so the alleged dependence is elusive. Moreover, the antecedent describes no real scenario (a point from Welty), and Leftow’s voluntarism — God could have willed otherwise — simply begs the question against deity theorists.")

setb("Objection 3", "Patrick Grim argues that omniscience requires a set of all truths, but by Cantor’s theorem any such set’s power set is larger — each subset yielding a further truth — so there is no set of all truths and no omniscience. Feser reports three replies: Plantinga’s, that the argument **proves too much** (it would rule out a set of all propositions, yet we coherently say all propositions are true or false); Simmons’s, that even without a set, no *particular* truth need be unknown to God; and Wainwright’s, that Grim assumes God’s knowledge is a set of discrete ideas, whereas on **divine simplicity** these are one reality in God described in different ways.")

setb("Objection 4", "Some Scholastics, like Peter Coffey, accept Scholastic realism but deny it can *prove* God. Coffey says the argument presupposes that possibilities are eternally and necessarily possible — knowable only if we already knew of a necessary intellect — and that a mind-independent order of abstract objects is a Platonic illusion. Feser replies that even an atheist Platonist grants eternal, necessary possibilities, so no divine intellect is presupposed; and Coffey himself believes such an order exists in God, so only its Platonic interpretation could be illusory. The implied dilemma — Platonic realm (false) or divine ideas (question-begging) — is a **false choice**: one can affirm an order of abstract objects existing in *some* way independent of all finite minds while leaving open what way, which is exactly the common ground on which Platonists and Scholastics debate.")

json.dump(d, open(p, 'w', encoding='utf-8'), ensure_ascii=False, indent=2)
print(sum(len(s['body'].split()) for s in d['summary']))
